// SPDX-License-Identifier: Apache-2.0
//
// Clears every generated input a capture run accumulates, before that run starts. Without this,
// three concrete false-evidence paths are possible: a manifest entry removed since the last run
// leaves its old result file behind (the report shows a state that no longer exists); an entry
// with reduced viewport coverage leaves stale results for the dropped viewports; and a prior
// `visual:ai-review` run's output (`ai-review-results.json`) survives into a later,
// AI-review-disabled pass, making that pass's report claim AI review ran when it didn't.
//
// Deliberately does NOT clear `report.md`/`report.json` — those are wholly regenerated by
// `generate-report.mjs` on every run and never read as an input, so there's nothing to
// contaminate; leaving them in place between runs is just a convenience (e.g. `visual:view-report`
// still has something to show immediately after a `visual:capture`-only run).
//
// Wired as this module's `previsual:capture` npm pre-hook (see package.json) — every
// `npm run visual:capture` starts from a clean slate automatically; this script does not need to
// be run manually.

import { existsSync, mkdirSync, rmSync } from 'node:fs';
import { join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = fileURLToPath(new URL('.', import.meta.url));
const OUTPUT_DIR = resolve(here, '..', '..', 'visual-output');

const PATHS_TO_CLEAR = [
  join(OUTPUT_DIR, 'results'),
  join(OUTPUT_DIR, 'screenshots'),
  join(OUTPUT_DIR, 'ai-review-results.json'),
  join(OUTPUT_DIR, 'expected-inventory.json'),
];

export function clearVisualOutput() {
  for (const path of PATHS_TO_CLEAR) {
    if (existsSync(path)) {
      rmSync(path, { recursive: true, force: true });
    }
  }
  mkdirSync(join(OUTPUT_DIR, 'results'), { recursive: true });
  mkdirSync(join(OUTPUT_DIR, 'screenshots'), { recursive: true });
  console.log('[clean-output] cleared visual-output/results, screenshots, ai-review-results.json, expected-inventory.json');
}

// CLI entry, guarded so `clearVisualOutput` can also be imported directly — see
// scripts/visual/global-setup.mjs, which calls it from Playwright's own `globalSetup` hook so the
// clear-before-every-run guarantee holds regardless of whether `playwright.visual.config.ts` is
// invoked via `npm run visual:capture` (whose `previsual:capture` pre-hook also runs this script)
// or directly via `npx playwright test --config=playwright.visual.config.ts`, which bypasses npm
// pre-hooks entirely — without this guard, importing this module for its function would also
// re-run the CLI's own console/process side effects.
if (process.argv[1] && fileURLToPath(import.meta.url) === resolve(process.argv[1])) {
  clearVisualOutput();
}
