// SPDX-License-Identifier: Apache-2.0

import type { NodeKind } from '../model/nodeKinds';

export const NODE_LABELS: Record<NodeKind, string> = {
  ASK_USER: 'Ask a Question',
  AI_STEP: 'AI Step',
  AI_DEBATE: 'AI with Tools',
  DECISION: 'Decision',
  REPEAT: 'Loop / Repeat',
  REUSE_WORKFLOW: 'Reuse Existing Workflow',
  LOAD_RESOURCE: 'Load External Resource',
  STOP: 'Stop with Error',
  RETRY: 'Retry Previous Step',
  SAVE_RESULT: 'Save Result',
};

export const NODE_DESCRIPTIONS: Record<NodeKind, string> = {
  ASK_USER: 'Collect input from the person running the workflow.',
  AI_STEP: 'Run an AI prompt and capture its output.',
  AI_DEBATE: 'Run an AI step that can call tools and external resources.',
  DECISION: 'Choose a path based on a condition.',
  REPEAT: 'Repeat a section of the workflow.',
  REUSE_WORKFLOW: 'Run another workflow as a step.',
  LOAD_RESOURCE: 'Reference an external resource (data, API, document).',
  STOP: 'Stop the workflow with an error message.',
  RETRY: 'Retry an earlier step.',
  SAVE_RESULT: "Save the workflow's result.",
};

export const ACTION_LABELS = {
  validate: 'Check Workflow',
  validating: 'Checking...',
  clientValidation: 'Workflow Problems',
  serverValidation: 'Server Problems',
  reuseWorkflow: 'Reuse Existing Workflow',
  saveDraft: 'Save draft',
  save: 'Save',
  saving: 'Saving…',
  run: 'Run',
  running: 'Running…',
  publish: 'Publish',
  publishing: 'Publishing…',
  import: 'Import',
  importing: 'Importing…',
  export: 'Export',
  exporting: 'Exporting…',
  install: 'Install',
  downloadBundle: 'Download bundle',
  looksGood: 'Looks good',
  thingsToFix: (count: number) => (count === 1 ? '1 thing to fix' : `${count} things to fix`),
  unsavedChanges: 'Unsaved changes',
  upToDate: 'Up to date',
  validationIssues: 'Validation issues',
  builderTitle: 'Workflow Builder',
  aiAssist: 'Build with AI',
  guidedMode: 'Guided',
  advancedMode: 'Advanced',
  deleteStep: 'Delete step',
  selectStartStep: 'Select start step',
  fixIssue: 'Fix',
  workflowLooksGood: 'Workflow looks good',
  configureStepClose: 'Configure this step and close when done.',
  nameField: 'Name',
  typeField: 'Type',
  descriptionField: 'Description',
  questionField: 'Question',
  agentField: 'Agent',
  agentPlaceholder: 'Agent id',
  instructionsField: 'Instructions',
  approvalField: 'Approval',
  approvalAutomatic: 'Automatic',
  approvalReview: 'Requires human review',
  approvalRequired: 'Requires human approval',
  approvalHelp:
    "When set to 'Requires human approval', the workflow pauses here for a person to review before continuing.",
  basicsSection: 'Basics',
  inputsOutputsSection: 'Inputs / Outputs',
  behaviorSection: 'Behavior',
  advancedSection: 'Advanced',
  addField: 'Add field',
  removeField: 'Remove field',
  resultNameField: 'Result name',
  resourcePathField: 'Resource path',
  resultContextKeyField: 'Result name (context key)',
  reasonField: 'Reason',
  targetStepField: 'Target step',
  fallbackTargetField: 'Fallback target',
  maxRetriesField: 'Max retries',
  maxAttemptsField: 'Max attempts',
  primaryAgentField: 'Primary agent',
  challengerAgentField: 'Challenger agent',
  maxRoundsField: 'Max rounds',
  resolutionInstructionsField: 'Resolution instructions',
  contextKeyField: 'Context key',
  contextKeyHint: 'Use the key of a value the previous step stored in context.',
  caseLabelPlaceholder: 'Case label',
  caseValuePlaceholder: 'Case value',
  connectsToField: 'Connects to',
  addCase: 'Add case',
  removeCase: 'Remove case',
  defaultBranchTargetField: 'Default branch target',
  loopModeField: 'Mode',
  maxIterationsField: 'Max iterations',
  listContextKeyField: 'List context key',
  evaluatorAgentField: 'Evaluator agent',
  maxIterationsActionField: 'When max iterations reached',
  loopBodyReadOnly:
    'This step is inside a loop body. Nested editing is not ready yet, so its fields are read-only.',
  advancedStepsGuided: 'Advanced steps (for power users)',
  advancedSteps: 'Advanced steps',
  addStep: 'Add step',
  chooseStepDescription: 'Choose a step to add to your workflow.',
  selectPlaceholder: 'Select…',
  unsupportedBannerTitle:
    'Some advanced workflow parts are shown read-only because editing support is not ready yet.',
  builderTipsTitle: 'Builder tips',
  builderTipSelect: 'Select a step to configure it in the side panel.',
  builderTipConnect: 'Drag from a connection port to link steps — arrows show execution order.',
  builderTipLibrary: 'Open the step library on the left to add more steps.',
  dismissTips: 'Dismiss builder tips',
  otherwiseBranch: 'Otherwise',
  loopBodyTitle: 'Loop body',
  loopBodyEmpty: 'Connect steps inside this loop.',
  workflowIdLabel: 'Workflow id',
  workflowNameLabel: 'Workflow name',
  workflowNamePlaceholder: 'Workflow name',
  workflowIdPlaceholder: 'workflow-id',
  modePickerTitle: 'How would you like to build?',
  modePickerGuidedHint: 'A simple checklist places each step on the canvas for you.',
  modePickerAdvancedHint: 'Full step library and every setting from the start.',
  validationDetailsDescription: 'Review problems and jump to the step that needs a fix.',
  formFieldsHint: 'Form fields are listed below; each needs a label and key.',
  fixedCountMode: 'Fixed count',
  forEachMode: 'For each item',
  agentSignalMode: 'Until AI says done',
  evaluatorMode: 'Evaluator says done',
  awaitUserAction: 'Ask user',
  failAction: 'Stop with error',
  okShort: 'OK',
  checkmarkOk: '✓ OK',
  behaviourTypeField: 'Behaviour type (wire)',
  behaviourTypeSaveResultNote: 'SAVE_RESULT is a canvas-only step; export maps it via workflow result handling.',
  behaviourTypeRepeatNote: 'REPEAT is a canvas-only loop container; inner steps map to wire behaviours individually.',
  flowSection: 'Flow',
  runsAfterField: 'Runs after',
  runsAfterStartOption: 'Start (first step)',
  runsAfterMultiplePredecessors:
    'This step has more than one step leading into it, so its position cannot be changed here. Adjust the connections on the canvas.',
  runsAfterMultipleSuccessors:
    'This step leads to more than one step, so its position cannot be changed here. Adjust the connections on the canvas.',
  runsAfterNoTargets: 'There are no other steps to run this after yet.',
  insertStepHere: 'Insert a step here',
  unreachableWarning: (name: string) =>
    `"${name}" is not connected to the start, so it will not run. Connect it to an earlier step.`,
  readOnlyBadge: 'Read-only',
  readOnlyBadgeTitle: 'This workflow is read-only. Steps can be viewed but not changed.',
  incompleteRoutingError:
    'This workflow has an incomplete step connection (a decision branch or retry target is unset). Complete the highlighted routing to continue.',
  draftRestoredTitle: 'Restored your previous session',
  draftRestoredBody: 'We found unsaved changes from your last visit and restored them automatically.',
  startFresh: 'Start fresh',
  dismissDraftRestored: 'Dismiss',
};

export const PALETTE_GROUP_LABELS = {
  common: 'Common',
  flow: 'Flow',
  advanced: 'Advanced',
} as const;

export const BUILDER_COPY = {
  startHere: 'Start here — this step collects input from whoever runs the workflow.',
  useTemplate: 'Use a template',
  templateHint: 'Browse starter templates on the home page.',
  modePickerTitle: ACTION_LABELS.modePickerTitle,
  modePickerGuided: ACTION_LABELS.guidedMode,
  modePickerGuidedHint: ACTION_LABELS.modePickerGuidedHint,
  modePickerAdvanced: ACTION_LABELS.advancedMode,
  modePickerAdvancedHint: ACTION_LABELS.modePickerAdvancedHint,
  paletteTitle: 'Steps',
  expandPalette: 'Expand step library',
  collapsePalette: 'Collapse step library',
  validationDetails: 'Validation details',
  stepLibrary: 'Step library',
};

export const EDGE_LABELS = {
  approvalGate: 'Human approval',
  reviewGate: 'Human review',
};

export const NODE_STATUS_LABELS = {
  valid: 'Ready',
  hasIssues: 'Needs attention',
  needsApproval: 'Approval required',
};

export const ISSUE_REWRITES: Record<string, string> = {
  'workflow id is required': 'Add a workflow ID before validating.',
  'workflow name is required': 'Give your workflow a name.',
  'at least one step is required': 'Add at least one step to the workflow.',
  'step name is required': 'Name this step so it is easier to understand.',
  'must be >= 1': 'Use a value of 1 or more.',
};

export const GUIDED_STAGE_LABELS = {
  addInput: 'Add input',
  configureInput: 'Configure input',
  addAiStep: 'Add AI step',
  addApproval: 'Add approval',
  requireApproval: 'Require approval',
  generateResult: 'Generate result',
  addSaveStep: 'Add save step',
};
