// SPDX-License-Identifier: Apache-2.0
//
// Tests for the attribution-term separation vocabulary. Proves the gate blocks phrasing
// that credits an assistant/model/tool with authoring committed work, while leaving bare,
// legitimate provider mentions (the actual point of a framework that supports pluggable
// LLM providers) alone.

import {test} from 'node:test';
import assert from 'node:assert/strict';
import {findAttributionLeaks, ATTRIBUTION_BLOCKED} from './attribution-terms.mjs';

test('flags a Co-Authored-By trailer naming a tool', () => {
  const hits = findAttributionLeaks('Co-Authored-By: Claude <noreply@anthropic.com>');
  assert.equal(hits.length, 1);
  assert.equal(hits[0].id, 'co-authored-by-tool');
});

test('flags a Claude Code session link', () => {
  assert.ok(findAttributionLeaks('See https://claude.ai/code/session_abc123').some((h) => h.id === 'claude-session-link'));
});

test('flags "written by <tool>" and "reviewed by <tool>" phrasing', () => {
  assert.ok(findAttributionLeaks('This module was written by ChatGPT.').some((h) => h.id === 'verb-then-tool'));
  assert.ok(findAttributionLeaks('Reviewed by Claude before merge.').some((h) => h.id === 'verb-then-tool'));
  assert.ok(findAttributionLeaks('Generated by an AI assistant.').some((h) => h.id === 'verb-then-tool'));
});

test('flags "<tool> wrote/implemented/reviewed" phrasing', () => {
  assert.ok(findAttributionLeaks('Claude implemented this function.').some((h) => h.id === 'tool-then-verb'));
  assert.ok(findAttributionLeaks('Copilot generated the test cases.').some((h) => h.id === 'tool-then-verb'));
});

test('flags generic AI/LLM-authorship claims', () => {
  assert.ok(findAttributionLeaks('This README is AI-generated.').some((h) => h.id === 'ai-generated-claim'));
  assert.ok(findAttributionLeaks('An LLM-written summary follows.').some((h) => h.id === 'ai-generated-claim'));
});

test('does NOT flag a bare provider name with no authorship verb nearby', () => {
  assert.deepEqual(findAttributionLeaks('AgentForge4j supports Claude, ChatGPT, and Gemini as pluggable providers.'), []);
});

test('does NOT flag the llm-claude/llm-openai module names', () => {
  assert.deepEqual(findAttributionLeaks('Add the `llm-claude` and `llm-openai` provider modules to your build.'), []);
});

test('does NOT flag a provider matrix describing supported models', () => {
  assert.deepEqual(
    findAttributionLeaks('| Provider | Module |\n|---|---|\n| Claude | llm-claude |\n| Gemini | llm-gemini |'),
    [],
  );
});

test('reports the 1-based line number', () => {
  const hits = findAttributionLeaks('clean line\nCo-Authored-By: Claude');
  assert.equal(hits[0].line, 2);
});

test('the block list is non-empty', () => {
  assert.ok(ATTRIBUTION_BLOCKED.length >= 5);
});
