// SPDX-License-Identifier: Apache-2.0
//
// Hermetic tests for javadoc-seo.mjs against both a literal sample of real raw maven-javadoc-plugin
// output (confirmed against a real /javadoc/0.1.0/ build) and fixture composed-site directories.

import { test } from 'node:test';
import assert from 'node:assert/strict';
import { mkdirSync, mkdtempSync, readFileSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { applyJavadocSeo, injectJavadocOverviewSeo } from './javadoc-seo.mjs';

// A trimmed but structurally real sample — confirmed against a live-built /javadoc/0.1.0/ overview
// page: the exact `<html lang>` (no value) and `content="module index"` shapes maven-javadoc-plugin
// emits, with everything else maven-javadoc-plugin actually ships around them.
const RAW_MAVEN_JAVADOC_HTML = `<!DOCTYPE HTML>
<html lang>
<head>
<!-- Generated by javadoc (17) on Wed Jul 22 05:02:14 UTC 2026 -->
<title>Overview (AgentForge4j API (next))</title>
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta name="dc.created" content="2026-07-22">
<meta name="description" content="module index">
<meta name="generator" content="javadoc/ModuleIndexWriter">
<link rel="stylesheet" type="text/css" href="stylesheet.css" title="Style">
</head>
<body class="module-index-page">
<div class="header"><h1 class="title">AgentForge4j API (next)</h1></div>
</body>
</html>
`;

test('injectJavadocOverviewSeo fixes lang, replaces the generic description, and adds canonical/OG/Twitter (none of which exist in the raw output)', () => {
  const html = injectJavadocOverviewSeo(RAW_MAVEN_JAVADOC_HTML, {
    title: 'AgentForge4j API Reference — latest stable, 0.1.0',
    description: 'Generated Javadoc API reference for the AgentForge4j framework (latest stable, 0.1.0).',
    canonical: 'https://agentforge4j.org/javadoc/latest/',
    ogImage: 'https://agentforge4j.org/brand/icon-512.png',
    noindex: false,
  });
  assert.match(html, /<html lang="en">/);
  assert.doesNotMatch(html, /<html lang>/);
  assert.doesNotMatch(html, /content="module index"/);
  assert.match(html, /<meta name="description" content="Generated Javadoc API reference[^"]*">/);
  assert.match(html, /<link rel="canonical" href="https:\/\/agentforge4j\.org\/javadoc\/latest\/">/);
  assert.match(html, /<meta property="og:url" content="https:\/\/agentforge4j\.org\/javadoc\/latest\/">/);
  assert.match(html, /<meta property="og:image" content="https:\/\/agentforge4j\.org\/brand\/icon-512\.png">/);
  assert.match(html, /<meta name="twitter:card" content="summary">/);
  assert.doesNotMatch(html, /<meta name="robots"/);
  // Real Javadoc functionality (navigation, generated body) must survive untouched.
  assert.match(html, /<h1 class="title">AgentForge4j API \(next\)<\/h1>/);
});

test('injectJavadocOverviewSeo adds a noindex,follow robots tag when asked (the version currently mirrored by /latest/)', () => {
  const html = injectJavadocOverviewSeo(RAW_MAVEN_JAVADOC_HTML, {
    title: 'AgentForge4j API Reference — 0.1.0',
    description: 'Generated Javadoc API reference for the AgentForge4j framework (0.1.0).',
    canonical: 'https://agentforge4j.org/javadoc/0.1.0/',
    ogImage: 'https://agentforge4j.org/brand/icon-512.png',
    noindex: true,
  });
  assert.match(html, /<meta name="robots" content="noindex,follow">/);
  // Still self-canonical even while noindexed — the task's own chosen policy: noindex avoids
  // duplicate indexing without misrepresenting which version this content actually is.
  assert.match(html, /<link rel="canonical" href="https:\/\/agentforge4j\.org\/javadoc\/0\.1\.0\/">/);
});

test('injectJavadocOverviewSeo fails closed if the raw <html lang> pattern is not found (template drift)', () => {
  const drifted = RAW_MAVEN_JAVADOC_HTML.replace('<html lang>', '<html lang="en">');
  assert.throws(
    () =>
      injectJavadocOverviewSeo(drifted, {
        title: 't',
        description: 'd',
        canonical: 'https://agentforge4j.org/javadoc/next/',
        ogImage: 'https://agentforge4j.org/brand/icon-512.png',
      }),
    /expected the raw `<html lang>`/,
  );
});

test('injectJavadocOverviewSeo fails closed if the generic "module index" description is not found (template drift)', () => {
  const drifted = RAW_MAVEN_JAVADOC_HTML.replace('content="module index"', 'content="something else"');
  assert.throws(
    () =>
      injectJavadocOverviewSeo(drifted, {
        title: 't',
        description: 'd',
        canonical: 'https://agentforge4j.org/javadoc/next/',
        ogImage: 'https://agentforge4j.org/brand/icon-512.png',
      }),
    /expected the raw `content="module index"`/,
  );
});

function fixtureSiteDir(surfaces) {
  const root = mkdtempSync(join(tmpdir(), 'javadoc-seo-'));
  const siteDir = join(root, '_site');
  for (const mountPath of surfaces) {
    const dir = join(siteDir, ...mountPath.split('/'));
    mkdirSync(dir, { recursive: true });
    writeFileSync(join(dir, 'index.html'), RAW_MAVEN_JAVADOC_HTML, 'utf8');
  }
  return siteDir;
}

test('applyJavadocSeo updates next, latest, and every released version — self-canonical, indexable', () => {
  const siteDir = fixtureSiteDir(['javadoc/next', 'javadoc/latest', 'javadoc/0.1.0']);
  const updated = applyJavadocSeo({
    siteDir,
    siteUrl: 'https://agentforge4j.org',
    ogImage: 'https://agentforge4j.org/brand/icon-512.png',
    releasedVersions: ['0.1.0'],
  });
  assert.equal(updated, 3);

  const next = readFileSync(join(siteDir, 'javadoc', 'next', 'index.html'), 'utf8');
  assert.match(next, /<link rel="canonical" href="https:\/\/agentforge4j\.org\/javadoc\/next\/">/);
  assert.doesNotMatch(next, /<meta name="robots"/);

  const latest = readFileSync(join(siteDir, 'javadoc', 'latest', 'index.html'), 'utf8');
  assert.match(latest, /<link rel="canonical" href="https:\/\/agentforge4j\.org\/javadoc\/latest\/">/);
  assert.doesNotMatch(latest, /<meta name="robots"/);

  // 0.1.0 IS the version /latest/ currently mirrors (releasedVersions[0]) — noindex,follow to avoid
  // two indexable URLs with byte-identical content, per the task's own chosen policy.
  const pinned = readFileSync(join(siteDir, 'javadoc', '0.1.0', 'index.html'), 'utf8');
  assert.match(pinned, /<link rel="canonical" href="https:\/\/agentforge4j\.org\/javadoc\/0\.1\.0\/">/);
  assert.match(pinned, /<meta name="robots" content="noindex,follow">/);
});

test('once a newer version ships, the OLD newest version (no longer a duplicate of /latest/) becomes indexable again — no hardcoded version', () => {
  const siteDir = fixtureSiteDir(['javadoc/next', 'javadoc/latest', 'javadoc/0.1.0', 'javadoc/0.2.0']);
  applyJavadocSeo({
    siteDir,
    siteUrl: 'https://agentforge4j.org',
    ogImage: 'https://agentforge4j.org/brand/icon-512.png',
    // Newest-first, matching versions.json's own convention (and assembleSite's own latestSource pick).
    releasedVersions: ['0.2.0', '0.1.0'],
  });
  const nowOld = readFileSync(join(siteDir, 'javadoc', '0.1.0', 'index.html'), 'utf8');
  assert.doesNotMatch(nowOld, /<meta name="robots"/, '0.1.0 is no longer byte-identical to /latest/ once 0.2.0 exists — must not stay noindexed');

  const nowNewest = readFileSync(join(siteDir, 'javadoc', '0.2.0', 'index.html'), 'utf8');
  assert.match(nowNewest, /<meta name="robots" content="noindex,follow">/, '0.2.0 is now the version /latest/ mirrors');
});

test('fails closed when a declared surface\'s overview page is missing', () => {
  const siteDir = fixtureSiteDir(['javadoc/next', 'javadoc/latest']); // 0.1.0 missing entirely
  assert.throws(
    () =>
      applyJavadocSeo({
        siteDir,
        siteUrl: 'https://agentforge4j.org',
        ogImage: 'https://agentforge4j.org/brand/icon-512.png',
        releasedVersions: ['0.1.0'],
      }),
    /expected surface overview page missing/,
  );
});
