// SPDX-License-Identifier: Apache-2.0
//
// Hermetic tests for javadoc-seo.mjs against literal samples of real raw maven-javadoc-plugin
// output (confirmed against a real `javadoc` (JDK 17) run producing an overview/module-index page,
// a class page, a package-summary page, and an all-classes-index page) and fixture composed-site
// directories, covering every generated page kind, not only the surface overview.

import { test } from 'node:test';
import assert from 'node:assert/strict';
import { mkdirSync, mkdtempSync, readFileSync, symlinkSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { applyJavadocSeo, injectJavadocPageSeo, isWithinRoot } from './javadoc-seo.mjs';

// A trimmed but structurally real sample — confirmed against a live-built /javadoc/0.1.0/ overview
// page: the exact `<html lang>` (no value) and `content="module index"` shapes maven-javadoc-plugin
// emits, with everything else maven-javadoc-plugin actually ships around them.
const RAW_OVERVIEW_HTML = `<!DOCTYPE HTML>
<html lang>
<head>
<!-- Generated by javadoc (17) on Wed Jul 22 05:02:14 UTC 2026 -->
<title>Overview (AgentForge4j API (next))</title>
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta name="dc.created" content="2026-07-22">
<meta name="description" content="module index">
<meta name="generator" content="javadoc/ModuleIndexWriter">
<link rel="stylesheet" type="text/css" href="stylesheet.css" title="Style">
</head>
<body class="module-index-page">
<div class="header"><h1 class="title">AgentForge4j API (next)</h1></div>
</body>
</html>
`;

// A trimmed but structurally real sample of a class page — confirmed against a real `javadoc`
// (JDK 17) run: unlike the overview page above, nested pages already carry a correct
// `<html lang="en">` and a real (if generic-shaped) description — the known empty-lang/"module
// index" bug is specific to the overview page, never assumed present elsewhere.
function rawClassPageHtml({ title = 'Foo', description = 'declaration: package: com.example, class: Foo' } = {}) {
  return `<!DOCTYPE HTML>
<html lang="en">
<head>
<!-- Generated by javadoc (17) on Wed Jul 22 23:24:12 CEST 2026 -->
<title>${title}</title>
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
<meta name="dc.created" content="2026-07-22">
<meta name="description" content="${description}">
<meta name="generator" content="javadoc/ClassWriterImpl">
<link rel="stylesheet" type="text/css" href="../../stylesheet.css" title="Style">
</head>
<body class="class-declaration-page">
<main role="main"><h1 class="title">Class Foo</h1><div class="member-signature">public class <span class="element-name">Foo</span></div></main>
</body>
</html>
`;
}

function rawPackageSummaryHtml() {
  return `<!DOCTYPE HTML>
<html lang="en">
<head>
<title>com.example</title>
<meta name="description" content="declaration: package: com.example">
<meta name="generator" content="javadoc/PackageWriterImpl">
<link rel="stylesheet" type="text/css" href="../../stylesheet.css" title="Style">
</head>
<body class="package-declaration-page">
<main role="main"><h1 class="title">Package com.example</h1></main>
</body>
</html>
`;
}

function rawAllClassesIndexHtml() {
  return `<!DOCTYPE HTML>
<html lang="en">
<head>
<title>All Classes and Interfaces</title>
<meta name="description" content="class index">
<meta name="generator" content="javadoc/AllClassesIndexWriter">
<link rel="stylesheet" type="text/css" href="stylesheet.css" title="Style">
</head>
<body class="all-classes-index-page">
<main role="main"><h1 class="title">All Classes and Interfaces</h1></main>
</body>
</html>
`;
}

// A trimmed but structurally real sample of build-javadoc.mjs's own `writeSurfacesLanding` output
// (build-javadoc.mjs:120-161) — the one page in every surface that is NOT maven-javadoc-plugin
// output at all: hand-authored by this repo's own build script, real `<html lang="en">`, and (unlike
// every plugin-generated page) NO `<meta name="description">` tag whatsoever by design.
const RAW_SURFACES_LANDING_HTML = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <title>AgentForge4j API — surfaces</title>
  <style>
    body { font-family: system-ui, sans-serif; max-width: 50rem; margin: 2rem auto; padding: 0 1rem; line-height: 1.5; }
  </style>
</head>
<body>
  <h1>AgentForge4j API (next)</h1>
  <ul>
    <li><a href="./index.html">Core API (aggregate)</a></li>
  </ul>
</body>
</html>
`;

test('injectJavadocPageSeo fixes lang, replaces the generic description, and adds canonical/OG/Twitter (none of which exist in the raw overview output)', () => {
  const html = injectJavadocPageSeo(RAW_OVERVIEW_HTML, {
    title: 'AgentForge4j API Reference — latest stable, 0.1.0',
    description: 'Generated Javadoc API reference for the AgentForge4j framework (latest stable, 0.1.0).',
    canonical: 'https://agentforge4j.org/javadoc/latest/',
    ogImage: 'https://agentforge4j.org/brand/icon-512.png',
    noindex: false,
  });
  assert.match(html, /<html lang="en">/);
  assert.doesNotMatch(html, /<html lang>/);
  assert.doesNotMatch(html, /content="module index"/);
  assert.match(html, /<meta name="description" content="Generated Javadoc API reference[^"]*">/);
  assert.match(html, /<link rel="canonical" href="https:\/\/agentforge4j\.org\/javadoc\/latest\/">/);
  assert.match(html, /<meta property="og:url" content="https:\/\/agentforge4j\.org\/javadoc\/latest\/">/);
  assert.match(html, /<meta property="og:image" content="https:\/\/agentforge4j\.org\/brand\/icon-512\.png">/);
  assert.match(html, /<meta name="twitter:card" content="summary">/);
  assert.doesNotMatch(html, /<meta name="robots"/);
  // Real Javadoc functionality (navigation, generated body) must survive untouched.
  assert.match(html, /<h1 class="title">AgentForge4j API \(next\)<\/h1>/);
});

test('injectJavadocPageSeo leaves an already-correct lang="en" untouched on a nested page (only the overview page has the empty-lang bug — never assumed present elsewhere)', () => {
  const html = injectJavadocPageSeo(rawClassPageHtml(), {
    title: 'Foo — AgentForge4j API Reference (next)',
    description: 'Generated Javadoc API reference for the AgentForge4j framework (next) — Foo.',
    canonical: 'https://agentforge4j.org/javadoc/next/com/example/Foo.html',
    ogImage: 'https://agentforge4j.org/brand/icon-512.png',
  });
  assert.match(html, /<html lang="en">/);
  // Real generated navigation/body content must survive untouched.
  assert.match(html, /<h1 class="title">Class Foo<\/h1>/);
  assert.match(html, /public class <span class="element-name">Foo<\/span>/);
});

test('injectJavadocPageSeo replaces a nested page\'s own mechanical description ("declaration: package: ...") with a useful one, grounded in the page\'s own <title>', () => {
  const html = injectJavadocPageSeo(rawClassPageHtml(), {
    title: 'Foo — AgentForge4j API Reference (next)',
    description: 'Generated Javadoc API reference for the AgentForge4j framework (next) — Foo.',
    canonical: 'https://agentforge4j.org/javadoc/next/com/example/Foo.html',
    ogImage: 'https://agentforge4j.org/brand/icon-512.png',
  });
  assert.doesNotMatch(html, /declaration: package: com\.example, class: Foo/);
  assert.match(html, /<meta name="description" content="Generated Javadoc API reference for the AgentForge4j framework \(next\) — Foo\.">/);
});

test('injectJavadocPageSeo adds a noindex,follow robots tag when asked (the version currently mirrored by /latest/)', () => {
  const html = injectJavadocPageSeo(RAW_OVERVIEW_HTML, {
    title: 'AgentForge4j API Reference — 0.1.0',
    description: 'Generated Javadoc API reference for the AgentForge4j framework (0.1.0).',
    canonical: 'https://agentforge4j.org/javadoc/0.1.0/',
    ogImage: 'https://agentforge4j.org/brand/icon-512.png',
    noindex: true,
  });
  assert.match(html, /<meta name="robots" content="noindex,follow">/);
  // Still self-canonical even while noindexed — the task's own chosen policy: noindex avoids
  // duplicate indexing without misrepresenting which version this content actually is (never
  // canonicalized to /latest/).
  assert.match(html, /<link rel="canonical" href="https:\/\/agentforge4j\.org\/javadoc\/0\.1\.0\/">/);
});

test('injectJavadocPageSeo fails closed if neither the empty <html lang> nor a lang="..." shape is found (template drift)', () => {
  const drifted = RAW_OVERVIEW_HTML.replace('<html lang>', '<html>');
  assert.throws(
    () =>
      injectJavadocPageSeo(drifted, {
        title: 't',
        description: 'd',
        canonical: 'https://agentforge4j.org/javadoc/next/',
        ogImage: 'https://agentforge4j.org/brand/icon-512.png',
      }),
    /expected either `<html lang>` or `<html lang="\.\.\."/,
  );
});

test('injectJavadocPageSeo fails closed if there is no <meta name="description"> tag at all (template drift)', () => {
  const drifted = RAW_OVERVIEW_HTML.replace('<meta name="description" content="module index">\n', '');
  assert.throws(
    () =>
      injectJavadocPageSeo(drifted, {
        title: 't',
        description: 'd',
        canonical: 'https://agentforge4j.org/javadoc/next/',
        ogImage: 'https://agentforge4j.org/brand/icon-512.png',
      }),
    /expected a <meta name="description"/,
  );
});

test('injectJavadocPageSeo inserts a fresh description tag (rather than failing closed) when allowMissingDescription is set — the one recognized non-plugin page (surfaces.html) genuinely has no description tag to replace', () => {
  const html = injectJavadocPageSeo(RAW_SURFACES_LANDING_HTML, {
    title: 'AgentForge4j API — surfaces — AgentForge4j API Reference (next, in-development)',
    description:
      'Generated Javadoc API reference for the AgentForge4j framework (next, in-development) — AgentForge4j API — surfaces.',
    canonical: 'https://agentforge4j.org/javadoc/next/surfaces.html',
    ogImage: 'https://agentforge4j.org/brand/icon-512.png',
    allowMissingDescription: true,
  });
  assert.match(html, /<meta name="description" content="Generated Javadoc API reference[^"]*">/);
  assert.equal((html.match(/<meta name="description"/g) ?? []).length, 1, 'exactly one description tag, never a duplicate');
  assert.match(html, /<link rel="canonical" href="https:\/\/agentforge4j\.org\/javadoc\/next\/surfaces\.html">/);
  // Real hand-authored content must survive untouched.
  assert.match(html, /<h1>AgentForge4j API \(next\)<\/h1>/);
});

test('injectJavadocPageSeo still fails closed on a description-less page when allowMissingDescription is not set (the default) — allowMissingDescription must not weaken the template-drift protection for ordinary pages', () => {
  assert.throws(
    () =>
      injectJavadocPageSeo(RAW_SURFACES_LANDING_HTML, {
        title: 't',
        description: 'd',
        canonical: 'https://agentforge4j.org/javadoc/next/surfaces.html',
        ogImage: 'https://agentforge4j.org/brand/icon-512.png',
      }),
    /expected a <meta name="description"/,
  );
});

test('injectJavadocPageSeo safely handles a title/description containing literal replacement-pattern sequences ($&, $`, $\') — proves the function-replacer fix, not accidental String.replace pattern interpolation', () => {
  const html = injectJavadocPageSeo(RAW_OVERVIEW_HTML, {
    title: "Weird $& Title $` End $'",
    description: "desc $& more $` text $'",
    canonical: 'https://agentforge4j.org/javadoc/next/',
    ogImage: 'https://agentforge4j.org/brand/icon-512.png',
  });
  assert.ok(html.includes('<meta name="description" content="desc $&amp; more $` text $\'">'));
  assert.ok(html.includes('<meta property="og:title" content="Weird $&amp; Title $` End $\'">'));
});

test('injectJavadocPageSeo fails closed with a clear "already processed" error rather than silently duplicating tags on a page that already has a canonical', () => {
  const once = injectJavadocPageSeo(RAW_OVERVIEW_HTML, {
    title: 't',
    description: 'd',
    canonical: 'https://agentforge4j.org/javadoc/next/',
    ogImage: 'https://agentforge4j.org/brand/icon-512.png',
  });
  assert.throws(
    () =>
      injectJavadocPageSeo(once, {
        title: 't2',
        description: 'd2',
        canonical: 'https://agentforge4j.org/javadoc/next/',
        ogImage: 'https://agentforge4j.org/brand/icon-512.png',
      }),
    /already has a <link rel="canonical"> tag — refusing to insert duplicate SEO tags/,
  );
  // And no duplicate tags were actually written to `once` by the first (successful) call itself.
  assert.equal((once.match(/<link rel="canonical"/g) ?? []).length, 1);
  assert.equal((once.match(/<meta property="og:title"/g) ?? []).length, 1);
});

test('injectJavadocPageSeo escapes adversarial title/description/canonical/image values in every attribute it writes', () => {
  const html = injectJavadocPageSeo(RAW_OVERVIEW_HTML, {
    title: 'Evil"><script>alert(1)</script>',
    description: 'desc & "quoted" <tag>',
    canonical: 'https://agentforge4j.org/javadoc/next/?x="><script>alert(2)</script>',
    ogImage: 'https://agentforge4j.org/brand/icon-512.png?x="onerror=alert(3)',
  });
  assert.ok(!/<script>/.test(html), 'no live <script> element may appear anywhere in the generated output');
  // The dangerous quote in the middle of the image value must itself be escaped (not the tag's own
  // legitimate closing quote, which always renders as `"` regardless of escaping).
  assert.match(html, /<meta property="og:image" content="https:\/\/agentforge4j\.org\/brand\/icon-512\.png\?x=&quot;onerror=alert\(3\)">/);
  assert.match(html, /<meta property="og:title" content="Evil&quot;&gt;&lt;script&gt;alert\(1\)&lt;\/script&gt;">/);
  assert.match(html, /<meta name="description" content="desc &amp; &quot;quoted&quot; &lt;tag&gt;">/);
});

function fixtureSiteDir(surfaces) {
  const root = mkdtempSync(join(tmpdir(), 'javadoc-seo-'));
  const siteDir = join(root, '_site');
  for (const mountPath of surfaces) {
    const dir = join(siteDir, ...mountPath.split('/'));
    mkdirSync(dir, { recursive: true });
    writeFileSync(join(dir, 'index.html'), RAW_OVERVIEW_HTML, 'utf8');
  }
  return siteDir;
}

/** Every real applyJavadocSeo call always processes `javadoc/next`, `javadoc/latest`, and one
 * `javadoc/<v>` per `releasedVersions` entry — this fixture always creates that full, real set (a
 * plain overview-only page for the surfaces not under test), with `targetMountPath` given a real
 * nested tree (package summary, class page, all-classes index) two levels deep — the same shape a
 * real `javadoc` (JDK 17) run produces for a single package — so tests can assert on nested-page
 * behavior for one specific surface without applyJavadocSeo failing on the other, unrelated,
 * always-required surfaces. */
function fixtureSiteDirWithNestedPages(targetMountPath, releasedVersions = ['0.1.0']) {
  const root = mkdtempSync(join(tmpdir(), 'javadoc-seo-nested-'));
  const siteDir = join(root, '_site');
  const allMountPaths = ['javadoc/next', 'javadoc/latest', ...releasedVersions.map((version) => `javadoc/${version}`)];
  for (const mountPath of allMountPaths) {
    const dir = join(siteDir, ...mountPath.split('/'));
    mkdirSync(dir, { recursive: true });
    writeFileSync(join(dir, 'index.html'), RAW_OVERVIEW_HTML, 'utf8');
  }
  const surfaceRoot = join(siteDir, ...targetMountPath.split('/'));
  mkdirSync(join(surfaceRoot, 'com', 'example'), { recursive: true });
  writeFileSync(join(surfaceRoot, 'index.html'), RAW_OVERVIEW_HTML, 'utf8');
  writeFileSync(join(surfaceRoot, 'allclasses-index.html'), rawAllClassesIndexHtml(), 'utf8');
  writeFileSync(join(surfaceRoot, 'com', 'example', 'package-summary.html'), rawPackageSummaryHtml(), 'utf8');
  writeFileSync(join(surfaceRoot, 'com', 'example', 'Foo.html'), rawClassPageHtml(), 'utf8');
  // A non-HTML asset alongside — must remain byte-identical.
  writeFileSync(join(surfaceRoot, 'stylesheet.css'), 'body { color: black; }\n', 'utf8');
  return { siteDir, surfaceRoot };
}

test('applyJavadocSeo updates next, latest, and every released version\'s overview page — self-canonical, indexable', () => {
  const siteDir = fixtureSiteDir(['javadoc/next', 'javadoc/latest', 'javadoc/0.1.0']);
  const updated = applyJavadocSeo({
    siteDir,
    siteUrl: 'https://agentforge4j.org',
    ogImage: 'https://agentforge4j.org/brand/icon-512.png',
    releasedVersions: ['0.1.0'],
  });
  assert.equal(updated, 3);

  const next = readFileSync(join(siteDir, 'javadoc', 'next', 'index.html'), 'utf8');
  assert.match(next, /<link rel="canonical" href="https:\/\/agentforge4j\.org\/javadoc\/next\/">/);
  assert.doesNotMatch(next, /<meta name="robots"/);

  const latest = readFileSync(join(siteDir, 'javadoc', 'latest', 'index.html'), 'utf8');
  assert.match(latest, /<link rel="canonical" href="https:\/\/agentforge4j\.org\/javadoc\/latest\/">/);
  assert.doesNotMatch(latest, /<meta name="robots"/);

  // 0.1.0 IS the version /latest/ currently mirrors (releasedVersions[0]) — noindex,follow to avoid
  // two indexable URLs with byte-identical content, per the task's own chosen policy.
  const pinned = readFileSync(join(siteDir, 'javadoc', '0.1.0', 'index.html'), 'utf8');
  assert.match(pinned, /<link rel="canonical" href="https:\/\/agentforge4j\.org\/javadoc\/0\.1\.0\/">/);
  assert.match(pinned, /<meta name="robots" content="noindex,follow">/);
});

test('applyJavadocSeo processes every nested page in the tree (package summary, class page, all-classes index), not only the surface overview', () => {
  const { siteDir } = fixtureSiteDirWithNestedPages('javadoc/next');
  const updated = applyJavadocSeo({
    siteDir,
    siteUrl: 'https://agentforge4j.org',
    ogImage: 'https://agentforge4j.org/brand/icon-512.png',
    releasedVersions: [],
  });
  // 4 pages under javadoc/next (index, allclasses-index, package-summary, Foo) + 1 under
  // javadoc/latest (its own plain overview, always processed alongside next) = 5.
  assert.equal(updated, 5, 'expected exactly the 5 real .html pages across next+latest in this fixture to be processed');

  const packageSummary = readFileSync(join(siteDir, 'javadoc', 'next', 'com', 'example', 'package-summary.html'), 'utf8');
  assert.match(packageSummary, /<link rel="canonical" href="https:\/\/agentforge4j\.org\/javadoc\/next\/com\/example\/package-summary\.html">/);
  assert.match(packageSummary, /<meta property="og:title"/);

  const classPage = readFileSync(join(siteDir, 'javadoc', 'next', 'com', 'example', 'Foo.html'), 'utf8');
  assert.match(classPage, /<link rel="canonical" href="https:\/\/agentforge4j\.org\/javadoc\/next\/com\/example\/Foo\.html">/);

  const allClasses = readFileSync(join(siteDir, 'javadoc', 'next', 'allclasses-index.html'), 'utf8');
  assert.match(allClasses, /<link rel="canonical" href="https:\/\/agentforge4j\.org\/javadoc\/next\/allclasses-index\.html">/);
});

test('page-relative canonical generation: a nested page canonicalizes to its own full relative path within the surface, never to the surface root or another surface', () => {
  const { siteDir } = fixtureSiteDirWithNestedPages('javadoc/latest');
  applyJavadocSeo({
    siteDir,
    siteUrl: 'https://agentforge4j.org',
    ogImage: 'https://agentforge4j.org/brand/icon-512.png',
    releasedVersions: [],
  });
  const classPage = readFileSync(join(siteDir, 'javadoc', 'latest', 'com', 'example', 'Foo.html'), 'utf8');
  assert.match(classPage, /<link rel="canonical" href="https:\/\/agentforge4j\.org\/javadoc\/latest\/com\/example\/Foo\.html">/);
  assert.doesNotMatch(classPage, /href="https:\/\/agentforge4j\.org\/javadoc\/latest\/"/, 'must not canonicalize to the surface root');
});

test('noindex,follow is applied to every page under the version currently mirrored by /latest/ — not only its overview', () => {
  const { siteDir } = fixtureSiteDirWithNestedPages('javadoc/0.1.0');
  applyJavadocSeo({
    siteDir,
    siteUrl: 'https://agentforge4j.org',
    ogImage: 'https://agentforge4j.org/brand/icon-512.png',
    releasedVersions: ['0.1.0'],
  });
  for (const relPath of ['index.html', 'allclasses-index.html', 'com/example/package-summary.html', 'com/example/Foo.html']) {
    const html = readFileSync(join(siteDir, 'javadoc', '0.1.0', ...relPath.split('/')), 'utf8');
    assert.match(html, /<meta name="robots" content="noindex,follow">/, `${relPath} must be noindex,follow (it duplicates /latest/)`);
  }
});

test('no robots tag appears anywhere under /javadoc/latest/** (always indexable, whole tree)', () => {
  const { siteDir } = fixtureSiteDirWithNestedPages('javadoc/latest');
  applyJavadocSeo({
    siteDir,
    siteUrl: 'https://agentforge4j.org',
    ogImage: 'https://agentforge4j.org/brand/icon-512.png',
    releasedVersions: [],
  });
  for (const relPath of ['index.html', 'allclasses-index.html', 'com/example/package-summary.html', 'com/example/Foo.html']) {
    const html = readFileSync(join(siteDir, 'javadoc', 'latest', ...relPath.split('/')), 'utf8');
    assert.doesNotMatch(html, /<meta name="robots"/, `${relPath} under /latest/ must never be noindexed`);
  }
});

test('once a newer version ships, the OLD newest version (no longer a duplicate of /latest/) becomes indexable again everywhere in its tree — no hardcoded version', () => {
  const siteDir = fixtureSiteDir(['javadoc/next', 'javadoc/latest', 'javadoc/0.1.0', 'javadoc/0.2.0']);
  applyJavadocSeo({
    siteDir,
    siteUrl: 'https://agentforge4j.org',
    ogImage: 'https://agentforge4j.org/brand/icon-512.png',
    // Newest-first, matching versions.json's own convention (and assembleSite's own latestSource pick).
    releasedVersions: ['0.2.0', '0.1.0'],
  });
  const nowOld = readFileSync(join(siteDir, 'javadoc', '0.1.0', 'index.html'), 'utf8');
  assert.doesNotMatch(nowOld, /<meta name="robots"/, '0.1.0 is no longer byte-identical to /latest/ once 0.2.0 exists — must not stay noindexed');

  const nowNewest = readFileSync(join(siteDir, 'javadoc', '0.2.0', 'index.html'), 'utf8');
  assert.match(nowNewest, /<meta name="robots" content="noindex,follow">/, '0.2.0 is now the version /latest/ mirrors');
});

test('applyJavadocSeo processes the real surfaces.html landing page (build-javadoc.mjs\'s own hand-authored, description-less page) without throwing — this is the exact real-corpus defect a full-tree compose caught: surfaces.html is otherwise indistinguishable from a genuine template-drift page missing its description', () => {
  const { siteDir, surfaceRoot } = fixtureSiteDirWithNestedPages('javadoc/next');
  writeFileSync(join(surfaceRoot, 'surfaces.html'), RAW_SURFACES_LANDING_HTML, 'utf8');
  const updated = applyJavadocSeo({
    siteDir,
    siteUrl: 'https://agentforge4j.org',
    ogImage: 'https://agentforge4j.org/brand/icon-512.png',
    releasedVersions: [],
  });
  assert.equal(updated, 6, 'the 5 pages from the base nested fixture plus the new surfaces.html');
  const surfacesPage = readFileSync(join(surfaceRoot, 'surfaces.html'), 'utf8');
  assert.match(surfacesPage, /<meta name="description" content="[^"]+">/);
  assert.match(surfacesPage, /<link rel="canonical" href="https:\/\/agentforge4j\.org\/javadoc\/next\/surfaces\.html">/);
  // Real hand-authored content must survive.
  assert.match(surfacesPage, /<h1>AgentForge4j API \(next\)<\/h1>/);
});

test('applyJavadocSeo names the offending file path when a genuinely description-less page is NOT the recognized surfaces.html landing page (template drift, still fails closed)', () => {
  const { siteDir, surfaceRoot } = fixtureSiteDirWithNestedPages('javadoc/next');
  // A description-less page under a different name must still fail loud — the error must name the
  // offending file, not just report a bare "template drift?" with no way to tell which of hundreds
  // of pages across three surfaces is the actual problem.
  writeFileSync(join(surfaceRoot, 'drifted-page.html'), RAW_SURFACES_LANDING_HTML, 'utf8');
  assert.throws(
    () =>
      applyJavadocSeo({
        siteDir,
        siteUrl: 'https://agentforge4j.org',
        ogImage: 'https://agentforge4j.org/brand/icon-512.png',
        releasedVersions: [],
      }),
    /failed processing .*drifted-page\.html.*expected a <meta name="description"/,
  );
});

test('a nested page\'s raw <title> containing HTML entities (e.g. a generic class like Foo<T>, which javadoc emits as Foo&lt;T&gt;) is decoded once and escaped exactly once — never double-escaped into literal "&lt;" text', () => {
  const { siteDir, surfaceRoot } = fixtureSiteDirWithNestedPages('javadoc/next');
  writeFileSync(
    join(surfaceRoot, 'com', 'example', 'Foo.html'),
    rawClassPageHtml({ title: 'Foo&lt;T&gt; &amp; Bar' }),
    'utf8',
  );
  applyJavadocSeo({
    siteDir,
    siteUrl: 'https://agentforge4j.org',
    ogImage: 'https://agentforge4j.org/brand/icon-512.png',
    releasedVersions: [],
  });
  const classPage = readFileSync(join(surfaceRoot, 'com', 'example', 'Foo.html'), 'utf8');
  // Semantically "Foo<T> & Bar" — escaped exactly once for HTML attribute embedding.
  assert.ok(
    classPage.includes(
      '<meta name="description" content="Generated Javadoc API reference for the AgentForge4j framework (next, in-development) — Foo&lt;T&gt; &amp; Bar.">',
    ),
  );
  assert.ok(
    classPage.includes(
      '<meta property="og:title" content="Foo&lt;T&gt; &amp; Bar — AgentForge4j API Reference (next, in-development)">',
    ),
  );
  assert.ok(!classPage.includes('&amp;lt;'), 'must never double-escape &lt; into &amp;lt; (renders as literal "&lt;" text)');
  assert.ok(!classPage.includes('&amp;gt;'), 'must never double-escape &gt; into &amp;gt;');
  assert.ok(!classPage.includes('&amp;amp;'), 'must never double-escape &amp; into &amp;amp;');
});

test('fails closed when a declared surface\'s overview page is missing', () => {
  const siteDir = fixtureSiteDir(['javadoc/next', 'javadoc/latest']); // 0.1.0 missing entirely
  assert.throws(
    () =>
      applyJavadocSeo({
        siteDir,
        siteUrl: 'https://agentforge4j.org',
        ogImage: 'https://agentforge4j.org/brand/icon-512.png',
        releasedVersions: ['0.1.0'],
      }),
    /expected surface overview page missing/,
  );
});

test('non-HTML assets (stylesheet.css) remain byte-identical after processing', () => {
  const { siteDir } = fixtureSiteDirWithNestedPages('javadoc/next');
  const before = readFileSync(join(siteDir, 'javadoc', 'next', 'stylesheet.css'), 'utf8');
  applyJavadocSeo({
    siteDir,
    siteUrl: 'https://agentforge4j.org',
    ogImage: 'https://agentforge4j.org/brand/icon-512.png',
    releasedVersions: [],
  });
  const after = readFileSync(join(siteDir, 'javadoc', 'next', 'stylesheet.css'), 'utf8');
  assert.equal(after, before);
});

test('nested Javadoc navigation/body content remains intact after processing (class page markup, real generated member signature)', () => {
  const { siteDir } = fixtureSiteDirWithNestedPages('javadoc/next');
  applyJavadocSeo({
    siteDir,
    siteUrl: 'https://agentforge4j.org',
    ogImage: 'https://agentforge4j.org/brand/icon-512.png',
    releasedVersions: [],
  });
  const classPage = readFileSync(join(siteDir, 'javadoc', 'next', 'com', 'example', 'Foo.html'), 'utf8');
  assert.match(classPage, /<h1 class="title">Class Foo<\/h1>/);
  assert.match(classPage, /public class <span class="element-name">Foo<\/span>/);
});

test('a full fixture tree reports the exact number of processed HTML pages (4 real pages under javadoc/next — overview, all-classes index, package summary, class page — plus 1 plain overview under javadoc/latest, always processed alongside it)', () => {
  const { siteDir } = fixtureSiteDirWithNestedPages('javadoc/next');
  const updated = applyJavadocSeo({
    siteDir,
    siteUrl: 'https://agentforge4j.org',
    ogImage: 'https://agentforge4j.org/brand/icon-512.png',
    releasedVersions: [],
  });
  assert.equal(updated, 5);
});

// --- isWithinRoot: the containment rule a symlinked directory/file's resolved target must satisfy
// before this module will follow it — directly testable without creating a real symlink (which
// requires elevated privileges on Windows, an environment concern this logic must not depend on to
// be verifiable) ---

test('isWithinRoot: a real descendant path is within root', () => {
  const root = join(tmpdir(), 'javadoc-root');
  assert.ok(isWithinRoot(root, join(root, 'com', 'example', 'Foo.html')));
  assert.ok(isWithinRoot(root, root));
});

test('isWithinRoot: a path reached via `..` traversal, or an unrelated sibling directory sharing the same string prefix, is rejected', () => {
  const root = join(tmpdir(), 'javadoc-root');
  assert.ok(!isWithinRoot(root, join(tmpdir(), 'secret.txt')));
  assert.ok(!isWithinRoot(root, join(tmpdir(), 'javadoc-root-evil', 'secret.txt')));
});

test('a symlinked directory pointing outside the surface root is refused, not silently followed (skipped in environments where creating a symlink requires elevated privileges, e.g. unconfigured Windows)', () => {
  const root = mkdtempSync(join(tmpdir(), 'javadoc-symlink-'));
  const siteDir = join(root, '_site');
  const surfaceRoot = join(siteDir, 'javadoc', 'next');
  mkdirSync(surfaceRoot, { recursive: true });
  writeFileSync(join(surfaceRoot, 'index.html'), RAW_OVERVIEW_HTML, 'utf8');
  const outsideDir = join(root, 'outside-the-surface');
  mkdirSync(outsideDir, { recursive: true });
  writeFileSync(join(outsideDir, 'secret.html'), RAW_OVERVIEW_HTML, 'utf8');

  let symlinkCreated = true;
  try {
    // 'junction' (not 'dir'): NTFS junctions don't require elevated privileges on Windows the way
    // true symbolic links do, so this test actually exercises the real containment check locally
    // instead of silently skipping — Node reports a junction identically to a symlink via
    // Dirent.isSymbolicLink(), so the code path under test is exactly the same either way.
    symlinkSync(outsideDir, join(surfaceRoot, 'escape'), 'junction');
  } catch (error) {
    if (error.code === 'EPERM' || error.code === 'EACCES') {
      symlinkCreated = false;
    } else {
      throw error;
    }
  }
  if (!symlinkCreated) {
    console.log('[javadoc-seo.test] symlink creation requires elevated privileges in this environment — skipping the live symlink assertion (isWithinRoot itself is covered by the two tests above)');
    return;
  }

  assert.throws(
    () =>
      applyJavadocSeo({
        siteDir,
        siteUrl: 'https://agentforge4j.org',
        ogImage: 'https://agentforge4j.org/brand/icon-512.png',
        releasedVersions: [],
      }),
    /refusing to follow a symlink that escapes the surface root/,
  );
});

test('a surface root reached only via a symlinked ancestor path still processes normally, with no in-root symlink involved (skipped where symlink creation requires elevated privileges, e.g. unconfigured Windows)', () => {
  const root = mkdtempSync(join(tmpdir(), 'javadoc-symlinked-ancestor-'));
  const realRoot = join(root, 'real');
  const siteDirReal = join(realRoot, '_site');
  for (const mountPath of ['javadoc/next', 'javadoc/latest']) {
    const dir = join(siteDirReal, ...mountPath.split('/'));
    mkdirSync(dir, { recursive: true });
    writeFileSync(join(dir, 'index.html'), RAW_OVERVIEW_HTML, 'utf8');
  }
  const nextSurfaceRoot = join(siteDirReal, 'javadoc', 'next');
  writeFileSync(join(nextSurfaceRoot, 'Foo.html'), rawClassPageHtml(), 'utf8');

  const aliasedRoot = join(root, 'aliased');
  let symlinkCreated = true;
  try {
    // 'junction': see the note on the escape-root test above.
    symlinkSync(realRoot, aliasedRoot, 'junction');
  } catch (error) {
    if (error.code === 'EPERM' || error.code === 'EACCES') {
      symlinkCreated = false;
    } else {
      throw error;
    }
  }
  if (!symlinkCreated) {
    console.log('[javadoc-seo.test] symlink creation requires elevated privileges in this environment — skipping the live symlinked-ancestor assertion (isWithinRoot itself is covered by the tests above)');
    return;
  }

  const siteDir = join(aliasedRoot, '_site');
  // Must NOT throw: every real file under the surface resolves inside the real surface root, and
  // that root is itself only reachable here via the symlinked `aliased` ancestor path — before the
  // PR172-006 fix, comparing a realpath'd symlink target against the unresolved `root` would have
  // spuriously failed the first symlink this walk ever encountered (there are none here — this
  // proves the ancestor-resolution fix in isolation, with no in-root symlink of its own).
  const updated = applyJavadocSeo({
    siteDir,
    siteUrl: 'https://agentforge4j.org',
    ogImage: 'https://agentforge4j.org/brand/icon-512.png',
    releasedVersions: [],
  });
  assert.equal(updated, 3, 'next: index + Foo (2), latest: index (1)');
});

// --- PR172-007: an in-root symlink can create two distinct walked paths that resolve to the SAME
// underlying real file or directory — walkHtmlFiles must refuse this outright rather than silently
// double-processing a page or recursing forever. ---

test('a symlinked HTML file is refused outright — ambiguous which of the two paths is the page\'s one real canonical URL (skipped where symlink creation requires elevated privileges)', () => {
  const { siteDir, surfaceRoot } = fixtureSiteDirWithNestedPages('javadoc/next');
  let symlinkCreated = true;
  try {
    symlinkSync(join(surfaceRoot, 'com', 'example', 'Foo.html'), join(surfaceRoot, 'Foo-alias.html'), 'file');
  } catch (error) {
    if (error.code === 'EPERM' || error.code === 'EACCES') {
      symlinkCreated = false;
    } else {
      throw error;
    }
  }
  if (!symlinkCreated) {
    console.log('[javadoc-seo.test] symlink creation requires elevated privileges in this environment — skipping');
    return;
  }
  assert.throws(
    () =>
      applyJavadocSeo({
        siteDir,
        siteUrl: 'https://agentforge4j.org',
        ogImage: 'https://agentforge4j.org/brand/icon-512.png',
        releasedVersions: [],
      }),
    /refusing to follow a symlinked HTML file \(ambiguous canonical URL\)/,
  );
});

test('a directory symlink pointing back at an ancestor (a cycle) is refused, not walked forever (skipped where symlink creation requires elevated privileges)', () => {
  const { siteDir, surfaceRoot } = fixtureSiteDirWithNestedPages('javadoc/next');
  let symlinkCreated = true;
  try {
    // com/example/back-to-root -> the surface root itself: walking into it would revisit `com`,
    // `com/example`, and `com/example/back-to-root` forever without cycle detection. 'junction':
    // see the note on the escape-root test above — runs for real locally, not just in CI.
    symlinkSync(surfaceRoot, join(surfaceRoot, 'com', 'example', 'back-to-root'), 'junction');
  } catch (error) {
    if (error.code === 'EPERM' || error.code === 'EACCES') {
      symlinkCreated = false;
    } else {
      throw error;
    }
  }
  if (!symlinkCreated) {
    console.log('[javadoc-seo.test] symlink creation requires elevated privileges in this environment — skipping');
    return;
  }
  assert.throws(
    () =>
      applyJavadocSeo({
        siteDir,
        siteUrl: 'https://agentforge4j.org',
        ogImage: 'https://agentforge4j.org/brand/icon-512.png',
        releasedVersions: [],
      }),
    /refusing to walk a directory whose real path was already visited/,
  );
});

test('two directory paths resolving to the same real directory (a real subtree plus a symlinked alias of it) are refused, not silently double-processed (skipped where symlink creation requires elevated privileges)', () => {
  const { siteDir, surfaceRoot } = fixtureSiteDirWithNestedPages('javadoc/next');
  let symlinkCreated = true;
  try {
    // "alias" is a second, independent path to the exact same real directory as com/example.
    // 'junction': see the note on the escape-root test above.
    symlinkSync(join(surfaceRoot, 'com', 'example'), join(surfaceRoot, 'alias'), 'junction');
  } catch (error) {
    if (error.code === 'EPERM' || error.code === 'EACCES') {
      symlinkCreated = false;
    } else {
      throw error;
    }
  }
  if (!symlinkCreated) {
    console.log('[javadoc-seo.test] symlink creation requires elevated privileges in this environment — skipping');
    return;
  }
  assert.throws(
    () =>
      applyJavadocSeo({
        siteDir,
        siteUrl: 'https://agentforge4j.org',
        ogImage: 'https://agentforge4j.org/brand/icon-512.png',
        releasedVersions: [],
      }),
    /refusing to walk a directory whose real path was already visited/,
  );
});
