// SPDX-License-Identifier: Apache-2.0
//
// Hermetic tests for javadoc-seo.mjs against literal samples of real raw maven-javadoc-plugin
// output (confirmed against a real `javadoc` (JDK 17) run producing an overview/module-index page,
// a class page, a package-summary page, and an all-classes-index page) and fixture composed-site
// directories, covering every generated page kind, not only the surface overview.

import { test } from 'node:test';
import assert from 'node:assert/strict';
import { mkdirSync, mkdtempSync, readFileSync, symlinkSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import {
  addRobotsNoindexTag,
  applyJavadocSeo,
  injectJavadocPageSeo,
  isJavadocRedirectStub,
  isWithinRoot,
  stripJavadocWindowTitle,
} from './javadoc-seo.mjs';

// A trimmed but structurally real sample — confirmed against a live-built /javadoc/0.1.0/ overview
// page: the exact `<html lang>` (no value) and `content="module index"` shapes maven-javadoc-plugin
// emits, with everything else maven-javadoc-plugin actually ships around them.
const RAW_OVERVIEW_HTML = `<!DOCTYPE HTML>
<html lang>
<head>
<!-- Generated by javadoc (17) on Wed Jul 22 05:02:14 UTC 2026 -->
<title>Overview (AgentForge4j API (next))</title>
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta name="dc.created" content="2026-07-22">
<meta name="description" content="module index">
<meta name="generator" content="javadoc/ModuleIndexWriter">
<link rel="stylesheet" type="text/css" href="stylesheet.css" title="Style">
</head>
<body class="module-index-page">
<div class="header"><h1 class="title">AgentForge4j API (next)</h1></div>
</body>
</html>
`;

// maven-javadoc-plugin appends the configured `-windowtitle` in parentheses to EVERY generated
// page's `<title>` — `Foo` is emitted as `Foo (AgentForge4j API (next))`, and so on for every page
// kind. The nested fixtures below previously omitted that suffix, which is precisely why no test
// could observe it being propagated into /latest/ and version-pinned titles/descriptions/og:titles:
// the fixtures were more "correct" than the generator. `WINDOW_TITLE` reproduces the real
// agentforge4j-docs-javadoc/pom.xml value so the corpus these tests run against is the one the
// build actually produces.
const WINDOW_TITLE = 'AgentForge4j API (next)';
const withWindowTitle = (pageTitle) => `${pageTitle} (${WINDOW_TITLE})`;

// A trimmed but structurally real sample of a class page. In a real full corpus, nested pages
// carry the same bare-`<html lang>` bug as the overview above (repaired identically — the
// bare-lang repair tests below cover that shape directly); this fixture deliberately carries a
// real `<html lang="en">` instead, to exercise the OTHER contract: a real lang value already
// present is left untouched, never assumed broken.
function rawClassPageHtml({
  title = withWindowTitle('Foo'),
  description = 'declaration: package: com.example, class: Foo',
} = {}) {
  return `<!DOCTYPE HTML>
<html lang="en">
<head>
<!-- Generated by javadoc (17) on Wed Jul 22 23:24:12 CEST 2026 -->
<title>${title}</title>
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
<meta name="dc.created" content="2026-07-22">
<meta name="description" content="${description}">
<meta name="generator" content="javadoc/ClassWriterImpl">
<link rel="stylesheet" type="text/css" href="../../stylesheet.css" title="Style">
</head>
<body class="class-declaration-page">
<main role="main"><h1 class="title">Class Foo</h1><div class="member-signature">public class <span class="element-name">Foo</span></div></main>
</body>
</html>
`;
}

function rawPackageSummaryHtml() {
  return `<!DOCTYPE HTML>
<html lang="en">
<head>
<title>com.example (AgentForge4j API (next))</title>
<meta name="description" content="declaration: package: com.example">
<meta name="generator" content="javadoc/PackageWriterImpl">
<link rel="stylesheet" type="text/css" href="../../stylesheet.css" title="Style">
</head>
<body class="package-declaration-page">
<main role="main"><h1 class="title">Package com.example</h1></main>
</body>
</html>
`;
}

function rawAllClassesIndexHtml() {
  return `<!DOCTYPE HTML>
<html lang="en">
<head>
<title>All Classes and Interfaces (AgentForge4j API (next))</title>
<meta name="description" content="class index">
<meta name="generator" content="javadoc/AllClassesIndexWriter">
<link rel="stylesheet" type="text/css" href="stylesheet.css" title="Style">
</head>
<body class="all-classes-index-page">
<main role="main"><h1 class="title">All Classes and Interfaces</h1></main>
</body>
</html>
`;
}

// A trimmed but structurally real sample of build-javadoc.mjs's own `writeSurfacesLanding` output
// (build-javadoc.mjs:120-161) — the one page in every surface that is NOT maven-javadoc-plugin
// output at all: hand-authored by this repo's own build script, real `<html lang="en">`, and (unlike
// every plugin-generated page) NO `<meta name="description">` tag whatsoever by design.
const RAW_SURFACES_LANDING_HTML = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <title>AgentForge4j API — surfaces</title>
  <style>
    body { font-family: system-ui, sans-serif; max-width: 50rem; margin: 2rem auto; padding: 0 1rem; line-height: 1.5; }
  </style>
</head>
<body>
  <h1>AgentForge4j API (next)</h1>
  <ul>
    <li><a href="./index.html">Core API (aggregate)</a></li>
  </ul>
</body>
</html>
`;

// A verbatim (trimmed only of nothing — this is the full page) sample of the legacy-URL redirect
// stub `javadoc (17)`'s IndexRedirectWriter emits as `overview-summary.html` at each javadoc root
// AND once per stitched sub-surface (confirmed against a real full corpus: 3 per surface) — the one
// raw plugin page kind that natively carries a `<link rel="canonical">` of its own. applyJavadocSeo
// must recognize and skip it whole: processing it would trip injectJavadocPageSeo's
// already-processed guard and abort the entire site assembly.
const RAW_REDIRECT_STUB_HTML = `<!DOCTYPE HTML>
<html lang>
<head>
<!-- Generated by javadoc (17) on Thu Jul 23 23:59:13 CEST 2026 -->
<title>AgentForge4j API (next)</title>
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta name="dc.created" content="2026-07-23">
<meta name="description" content="index redirect">
<meta name="generator" content="javadoc/IndexRedirectWriter">
<link rel="canonical" href="index.html">
<link rel="stylesheet" type="text/css" href="stylesheet.css" title="Style">
<script type="text/javascript">window.location.replace('index.html')</script>
<noscript>
<meta http-equiv="Refresh" content="0;index.html">
</noscript>
</head>
<body class="index-redirect-page">
<main role="main">
<noscript>
<p>JavaScript is disabled on your browser.</p>
</noscript>
<p><a href="index.html">index.html</a></p>
</main>
</body>
</html>
`;

test('injectJavadocPageSeo fixes lang, replaces the generic description, and adds canonical/OG/Twitter (none of which exist in the raw overview output)', () => {
  const html = injectJavadocPageSeo(RAW_OVERVIEW_HTML, {
    title: 'AgentForge4j API Reference — latest stable, 0.1.0',
    description: 'Generated Javadoc API reference for the AgentForge4j framework (latest stable, 0.1.0).',
    canonical: 'https://agentforge4j.org/javadoc/latest/',
    ogImage: 'https://agentforge4j.org/brand/icon-512.png',
    noindex: false,
  });
  assert.match(html, /<html lang="en">/);
  assert.doesNotMatch(html, /<html lang>/);
  assert.doesNotMatch(html, /content="module index"/);
  assert.match(html, /<meta name="description" content="Generated Javadoc API reference[^"]*">/);
  assert.match(html, /<link rel="canonical" href="https:\/\/agentforge4j\.org\/javadoc\/latest\/">/);
  assert.match(html, /<meta property="og:url" content="https:\/\/agentforge4j\.org\/javadoc\/latest\/">/);
  assert.match(html, /<meta property="og:image" content="https:\/\/agentforge4j\.org\/brand\/icon-512\.png">/);
  assert.match(html, /<meta name="twitter:card" content="summary">/);
  assert.doesNotMatch(html, /<meta name="robots"/);
  // The overview <h1> is maven-javadoc-plugin's rendering of the generated doc title, so it is
  // corrected to the same lifecycle-correct text as the <title> — see the doc-title heading tests.
  assert.match(html, /<h1 class="title">AgentForge4j API Reference — latest stable, 0\.1\.0<\/h1>/);
});

test('injectJavadocPageSeo leaves an already-correct lang="en" untouched (a real lang value is never assumed broken, whichever page carries it)', () => {
  const html = injectJavadocPageSeo(rawClassPageHtml(), {
    title: 'Foo — AgentForge4j API Reference (next)',
    description: 'Generated Javadoc API reference for the AgentForge4j framework (next) — Foo.',
    canonical: 'https://agentforge4j.org/javadoc/next/com/example/Foo.html',
    ogImage: 'https://agentforge4j.org/brand/icon-512.png',
  });
  assert.match(html, /<html lang="en">/);
  // Real generated navigation/body content must survive untouched.
  assert.match(html, /<h1 class="title">Class Foo<\/h1>/);
  assert.match(html, /public class <span class="element-name">Foo<\/span>/);
});

// --- empty/whitespace-only lang values must be repaired, never accepted as-is --------------------

function langAttrCount(html) {
  return (html.match(/\blang=/g) ?? []).length;
}

test('<html lang> (no = at all) is repaired to lang="en" — the known maven-javadoc-plugin bug shape', () => {
  const html = injectJavadocPageSeo(RAW_OVERVIEW_HTML, {
    title: 't',
    description: 'd',
    canonical: 'https://agentforge4j.org/javadoc/next/',
    ogImage: 'https://agentforge4j.org/brand/icon-512.png',
  });
  assert.match(html, /<html lang="en">/);
  assert.equal(langAttrCount(html), 1, 'expected exactly one lang= attribute after repair');
});

test('<html lang=""> (explicit empty value) is repaired to lang="en", not silently accepted as "already valid"', () => {
  const emptyValue = RAW_OVERVIEW_HTML.replace('<html lang>', '<html lang="">');
  const html = injectJavadocPageSeo(emptyValue, {
    title: 't',
    description: 'd',
    canonical: 'https://agentforge4j.org/javadoc/next/',
    ogImage: 'https://agentforge4j.org/brand/icon-512.png',
  });
  assert.match(html, /<html lang="en">/);
  assert.doesNotMatch(html, /<html lang="">/);
  assert.equal(langAttrCount(html), 1, 'expected exactly one lang= attribute after repair');
});

test('<html lang="   "> (whitespace-only value) is repaired identically to the empty-value case', () => {
  const whitespaceValue = RAW_OVERVIEW_HTML.replace('<html lang>', '<html lang="   ">');
  const html = injectJavadocPageSeo(whitespaceValue, {
    title: 't',
    description: 'd',
    canonical: 'https://agentforge4j.org/javadoc/next/',
    ogImage: 'https://agentforge4j.org/brand/icon-512.png',
  });
  assert.match(html, /<html lang="en">/);
  assert.doesNotMatch(html, /<html lang="   ">/);
  assert.equal(langAttrCount(html), 1, 'expected exactly one lang= attribute after repair');
});

test('<html lang="   "> repair also applies to a nested-page-shaped fixture (a real class page), not only the overview shape', () => {
  const whitespaceValue = rawClassPageHtml().replace('<html lang="en">', '<html lang="   ">');
  const html = injectJavadocPageSeo(whitespaceValue, {
    title: 'Foo — AgentForge4j API Reference (next)',
    description: 'Generated Javadoc API reference for the AgentForge4j framework (next) — Foo.',
    canonical: 'https://agentforge4j.org/javadoc/next/com/example/Foo.html',
    ogImage: 'https://agentforge4j.org/brand/icon-512.png',
  });
  assert.match(html, /<html lang="en">/);
  assert.equal(langAttrCount(html), 1, 'expected exactly one lang= attribute after repair');
  // Real generated content must still survive the repair untouched.
  assert.match(html, /<h1 class="title">Class Foo<\/h1>/);
});

test('a real, non-empty lang value (en-US) is preserved unchanged, not overwritten to "en"', () => {
  const html = injectJavadocPageSeo(rawClassPageHtml().replace('lang="en"', 'lang="en-US"'), {
    title: 'Foo — AgentForge4j API Reference (next)',
    description: 'Generated Javadoc API reference for the AgentForge4j framework (next) — Foo.',
    canonical: 'https://agentforge4j.org/javadoc/next/com/example/Foo.html',
    ogImage: 'https://agentforge4j.org/brand/icon-512.png',
  });
  assert.match(html, /<html lang="en-US">/);
  assert.doesNotMatch(html, /<html lang="en">/);
  assert.equal(langAttrCount(html), 1, 'expected exactly one lang= attribute');
});

test('injectJavadocPageSeo replaces a nested page\'s own mechanical description ("declaration: package: ...") with a useful one, grounded in the page\'s own <title>', () => {
  const html = injectJavadocPageSeo(rawClassPageHtml(), {
    title: 'Foo — AgentForge4j API Reference (next)',
    description: 'Generated Javadoc API reference for the AgentForge4j framework (next) — Foo.',
    canonical: 'https://agentforge4j.org/javadoc/next/com/example/Foo.html',
    ogImage: 'https://agentforge4j.org/brand/icon-512.png',
  });
  assert.doesNotMatch(html, /declaration: package: com\.example, class: Foo/);
  assert.match(html, /<meta name="description" content="Generated Javadoc API reference for the AgentForge4j framework \(next\) — Foo\.">/);
});

test('injectJavadocPageSeo adds a noindex,follow robots tag when asked (the version currently mirrored by /latest/)', () => {
  const html = injectJavadocPageSeo(RAW_OVERVIEW_HTML, {
    title: 'AgentForge4j API Reference — 0.1.0',
    description: 'Generated Javadoc API reference for the AgentForge4j framework (0.1.0).',
    canonical: 'https://agentforge4j.org/javadoc/0.1.0/',
    ogImage: 'https://agentforge4j.org/brand/icon-512.png',
    noindex: true,
  });
  assert.match(html, /<meta name="robots" content="noindex,follow">/);
  // Still self-canonical even while noindexed — the task's own chosen policy: noindex avoids
  // duplicate indexing without misrepresenting which version this content actually is (never
  // canonicalized to /latest/).
  assert.match(html, /<link rel="canonical" href="https:\/\/agentforge4j\.org\/javadoc\/0\.1\.0\/">/);
});

test('injectJavadocPageSeo fails closed if neither the empty <html lang> nor a lang="..." shape is found (template drift)', () => {
  const drifted = RAW_OVERVIEW_HTML.replace('<html lang>', '<html>');
  assert.throws(
    () =>
      injectJavadocPageSeo(drifted, {
        title: 't',
        description: 'd',
        canonical: 'https://agentforge4j.org/javadoc/next/',
        ogImage: 'https://agentforge4j.org/brand/icon-512.png',
      }),
    /expected either `<html lang>` or `<html lang="\.\.\."/,
  );
});

test('injectJavadocPageSeo fails closed if there is no <meta name="description"> tag at all (template drift)', () => {
  const drifted = RAW_OVERVIEW_HTML.replace('<meta name="description" content="module index">\n', '');
  assert.throws(
    () =>
      injectJavadocPageSeo(drifted, {
        title: 't',
        description: 'd',
        canonical: 'https://agentforge4j.org/javadoc/next/',
        ogImage: 'https://agentforge4j.org/brand/icon-512.png',
      }),
    /expected a <meta name="description"/,
  );
});

test('injectJavadocPageSeo inserts a fresh description tag (rather than failing closed) when allowMissingDescription is set — the one recognized non-plugin page (surfaces.html) genuinely has no description tag to replace', () => {
  const html = injectJavadocPageSeo(RAW_SURFACES_LANDING_HTML, {
    title: 'AgentForge4j API — surfaces — AgentForge4j API Reference (next, in-development)',
    description:
      'Generated Javadoc API reference for the AgentForge4j framework (next, in-development) — AgentForge4j API — surfaces.',
    canonical: 'https://agentforge4j.org/javadoc/next/surfaces.html',
    ogImage: 'https://agentforge4j.org/brand/icon-512.png',
    allowMissingDescription: true,
  });
  assert.match(html, /<meta name="description" content="Generated Javadoc API reference[^"]*">/);
  assert.equal((html.match(/<meta name="description"/g) ?? []).length, 1, 'exactly one description tag, never a duplicate');
  assert.match(html, /<link rel="canonical" href="https:\/\/agentforge4j\.org\/javadoc\/next\/surfaces\.html">/);
  // The landing page's own <h1> is the same generated doc title text, corrected identically; its
  // real hand-authored body content (the surface list) survives untouched.
  assert.match(html, /<h1>AgentForge4j API — surfaces — AgentForge4j API Reference \(next, in-development\)<\/h1>/);
  assert.match(html, /<li><a href="\.\/index\.html">Core API \(aggregate\)<\/a><\/li>/);
});

test('injectJavadocPageSeo still fails closed on a description-less page when allowMissingDescription is not set (the default) — allowMissingDescription must not weaken the template-drift protection for ordinary pages', () => {
  assert.throws(
    () =>
      injectJavadocPageSeo(RAW_SURFACES_LANDING_HTML, {
        title: 't',
        description: 'd',
        canonical: 'https://agentforge4j.org/javadoc/next/surfaces.html',
        ogImage: 'https://agentforge4j.org/brand/icon-512.png',
      }),
    /expected a <meta name="description"/,
  );
});

test('injectJavadocPageSeo safely handles a title/description containing literal replacement-pattern sequences ($&, $`, $\') — proves the function-replacer fix, not accidental String.replace pattern interpolation', () => {
  const html = injectJavadocPageSeo(RAW_OVERVIEW_HTML, {
    title: "Weird $& Title $` End $'",
    description: "desc $& more $` text $'",
    canonical: 'https://agentforge4j.org/javadoc/next/',
    ogImage: 'https://agentforge4j.org/brand/icon-512.png',
  });
  assert.ok(html.includes('<meta name="description" content="desc $&amp; more $` text $\'">'));
  assert.ok(html.includes('<meta property="og:title" content="Weird $&amp; Title $` End $\'">'));
});

test('injectJavadocPageSeo fails closed with a clear "already processed" error rather than silently duplicating tags on a page that already has a canonical', () => {
  const once = injectJavadocPageSeo(RAW_OVERVIEW_HTML, {
    title: 't',
    description: 'd',
    canonical: 'https://agentforge4j.org/javadoc/next/',
    ogImage: 'https://agentforge4j.org/brand/icon-512.png',
  });
  assert.throws(
    () =>
      injectJavadocPageSeo(once, {
        title: 't2',
        description: 'd2',
        canonical: 'https://agentforge4j.org/javadoc/next/',
        ogImage: 'https://agentforge4j.org/brand/icon-512.png',
      }),
    /already has a <link rel="canonical"> tag — refusing to insert duplicate SEO tags/,
  );
  // And no duplicate tags were actually written to `once` by the first (successful) call itself.
  assert.equal((once.match(/<link rel="canonical"/g) ?? []).length, 1);
  assert.equal((once.match(/<meta property="og:title"/g) ?? []).length, 1);
});

test('injectJavadocPageSeo escapes adversarial title/description/canonical/image values in every attribute it writes', () => {
  const html = injectJavadocPageSeo(RAW_OVERVIEW_HTML, {
    title: 'Evil"><script>alert(1)</script>',
    description: 'desc & "quoted" <tag>',
    canonical: 'https://agentforge4j.org/javadoc/next/?x="><script>alert(2)</script>',
    ogImage: 'https://agentforge4j.org/brand/icon-512.png?x="onerror=alert(3)',
  });
  assert.ok(!/<script>/.test(html), 'no live <script> element may appear anywhere in the generated output');
  // The dangerous quote in the middle of the image value must itself be escaped (not the tag's own
  // legitimate closing quote, which always renders as `"` regardless of escaping).
  assert.match(html, /<meta property="og:image" content="https:\/\/agentforge4j\.org\/brand\/icon-512\.png\?x=&quot;onerror=alert\(3\)">/);
  assert.match(html, /<meta property="og:title" content="Evil&quot;&gt;&lt;script&gt;alert\(1\)&lt;\/script&gt;">/);
  assert.match(html, /<meta name="description" content="desc &amp; &quot;quoted&quot; &lt;tag&gt;">/);
});

function fixtureSiteDir(surfaces) {
  const root = mkdtempSync(join(tmpdir(), 'javadoc-seo-'));
  const siteDir = join(root, '_site');
  for (const mountPath of surfaces) {
    const dir = join(siteDir, ...mountPath.split('/'));
    mkdirSync(dir, { recursive: true });
    writeFileSync(join(dir, 'index.html'), RAW_OVERVIEW_HTML, 'utf8');
  }
  return siteDir;
}

/** Every real applyJavadocSeo call always processes `javadoc/next`, `javadoc/latest`, and one
 * `javadoc/<v>` per `releasedVersions` entry — this fixture always creates that full, real set (a
 * plain overview-only page for the surfaces not under test), with `targetMountPath` given a real
 * nested tree (package summary, class page, all-classes index) two levels deep — the same shape a
 * real `javadoc` (JDK 17) run produces for a single package — so tests can assert on nested-page
 * behavior for one specific surface without applyJavadocSeo failing on the other, unrelated,
 * always-required surfaces. */
function fixtureSiteDirWithNestedPages(targetMountPath, releasedVersions = ['0.1.0']) {
  const root = mkdtempSync(join(tmpdir(), 'javadoc-seo-nested-'));
  const siteDir = join(root, '_site');
  const allMountPaths = ['javadoc/next', 'javadoc/latest', ...releasedVersions.map((version) => `javadoc/${version}`)];
  for (const mountPath of allMountPaths) {
    const dir = join(siteDir, ...mountPath.split('/'));
    mkdirSync(dir, { recursive: true });
    writeFileSync(join(dir, 'index.html'), RAW_OVERVIEW_HTML, 'utf8');
  }
  const surfaceRoot = join(siteDir, ...targetMountPath.split('/'));
  mkdirSync(join(surfaceRoot, 'com', 'example'), { recursive: true });
  writeFileSync(join(surfaceRoot, 'index.html'), RAW_OVERVIEW_HTML, 'utf8');
  writeFileSync(join(surfaceRoot, 'allclasses-index.html'), rawAllClassesIndexHtml(), 'utf8');
  writeFileSync(join(surfaceRoot, 'com', 'example', 'package-summary.html'), rawPackageSummaryHtml(), 'utf8');
  writeFileSync(join(surfaceRoot, 'com', 'example', 'Foo.html'), rawClassPageHtml(), 'utf8');
  // A non-HTML asset alongside — must remain byte-identical.
  writeFileSync(join(surfaceRoot, 'stylesheet.css'), 'body { color: black; }\n', 'utf8');
  return { siteDir, surfaceRoot };
}

test('applyJavadocSeo updates next, latest, and every released version\'s overview page — each self-canonical at its own URL', () => {
  const siteDir = fixtureSiteDir(['javadoc/next', 'javadoc/latest', 'javadoc/0.1.0']);
  const updated = applyJavadocSeo({
    siteDir,
    siteUrl: 'https://agentforge4j.org',
    ogImage: 'https://agentforge4j.org/brand/icon-512.png',
    releasedVersions: ['0.1.0'],
  });
  assert.equal(updated, 3);

  // /next/ is self-canonical but noindex in EVERY lifecycle state — it tracks main and is a
  // duplicate of /latest/ whenever main has not diverged from the newest release tag.
  const next = readFileSync(join(siteDir, 'javadoc', 'next', 'index.html'), 'utf8');
  assert.match(next, /<link rel="canonical" href="https:\/\/agentforge4j\.org\/javadoc\/next\/">/);
  assert.match(next, /<meta name="robots" content="noindex,follow">/);

  const latest = readFileSync(join(siteDir, 'javadoc', 'latest', 'index.html'), 'utf8');
  assert.match(latest, /<link rel="canonical" href="https:\/\/agentforge4j\.org\/javadoc\/latest\/">/);
  assert.doesNotMatch(latest, /<meta name="robots"/);

  // 0.1.0 IS the version /latest/ currently mirrors (releasedVersions[0]) — noindex,follow to avoid
  // two indexable URLs with byte-identical content, per the task's own chosen policy.
  const pinned = readFileSync(join(siteDir, 'javadoc', '0.1.0', 'index.html'), 'utf8');
  assert.match(pinned, /<link rel="canonical" href="https:\/\/agentforge4j\.org\/javadoc\/0\.1\.0\/">/);
  assert.match(pinned, /<meta name="robots" content="noindex,follow">/);
});

test('applyJavadocSeo processes every nested page in the tree (package summary, class page, all-classes index), not only the surface overview', () => {
  const { siteDir } = fixtureSiteDirWithNestedPages('javadoc/next');
  const updated = applyJavadocSeo({
    siteDir,
    siteUrl: 'https://agentforge4j.org',
    ogImage: 'https://agentforge4j.org/brand/icon-512.png',
    releasedVersions: [],
  });
  // 4 pages under javadoc/next (index, allclasses-index, package-summary, Foo) + 1 under
  // javadoc/latest (its own plain overview, always processed alongside next) = 5.
  assert.equal(updated, 5, 'expected exactly the 5 real .html pages across next+latest in this fixture to be processed');

  const packageSummary = readFileSync(join(siteDir, 'javadoc', 'next', 'com', 'example', 'package-summary.html'), 'utf8');
  assert.match(packageSummary, /<link rel="canonical" href="https:\/\/agentforge4j\.org\/javadoc\/next\/com\/example\/package-summary\.html">/);
  assert.match(packageSummary, /<meta property="og:title"/);

  const classPage = readFileSync(join(siteDir, 'javadoc', 'next', 'com', 'example', 'Foo.html'), 'utf8');
  assert.match(classPage, /<link rel="canonical" href="https:\/\/agentforge4j\.org\/javadoc\/next\/com\/example\/Foo\.html">/);

  const allClasses = readFileSync(join(siteDir, 'javadoc', 'next', 'allclasses-index.html'), 'utf8');
  assert.match(allClasses, /<link rel="canonical" href="https:\/\/agentforge4j\.org\/javadoc\/next\/allclasses-index\.html">/);
});

test('isJavadocRedirectStub recognizes the real IndexRedirectWriter stub and nothing else', () => {
  assert.equal(isJavadocRedirectStub(RAW_REDIRECT_STUB_HTML), true);
  assert.equal(isJavadocRedirectStub(RAW_OVERVIEW_HTML), false);
  assert.equal(isJavadocRedirectStub(rawClassPageHtml()), false);
  assert.equal(isJavadocRedirectStub(rawPackageSummaryHtml()), false);
  assert.equal(isJavadocRedirectStub(rawAllClassesIndexHtml()), false);
  assert.equal(isJavadocRedirectStub(RAW_SURFACES_LANDING_HTML), false);
});

// The deploy-killing shape a real corpus actually contains: javadoc's own redirect stubs sit at the
// surface root AND inside each stitched sub-surface, and each natively carries a canonical tag.
// Without the skip, applyJavadocSeo throws on the very first one ("already has a
// <link rel="canonical"> tag") and the whole site assembly dies — in BOTH lifecycle states.
function addRedirectStubs(surfaceRoot) {
  writeFileSync(join(surfaceRoot, 'overview-summary.html'), RAW_REDIRECT_STUB_HTML, 'utf8');
  mkdirSync(join(surfaceRoot, 'mcp'), { recursive: true });
  writeFileSync(join(surfaceRoot, 'mcp', 'overview-summary.html'), RAW_REDIRECT_STUB_HTML, 'utf8');
  writeFileSync(join(surfaceRoot, 'mcp', 'index.html'), RAW_OVERVIEW_HTML, 'utf8');
}

/** The stub with the robots tag added and NOTHING else changed — the exact expected output on a
 * noindex surface. Built from the raw stub itself so the assertion cannot drift from the fixture. */
const REDIRECT_STUB_WITH_ROBOTS = RAW_REDIRECT_STUB_HTML.replace(
  '</head>',
  '<meta name="robots" content="noindex,follow">\n</head>',
);

test('a redirect stub on a NOINDEX surface gains the robots tag and nothing else — the indexability policy cannot be escaped through a redirect shell', () => {
  const { siteDir, surfaceRoot } = fixtureSiteDirWithNestedPages('javadoc/next', []);
  addRedirectStubs(surfaceRoot);
  const updated = applyJavadocSeo({
    siteDir,
    siteUrl: 'https://agentforge4j.org',
    ogImage: 'https://agentforge4j.org/brand/icon-512.png',
    releasedVersions: [],
  });
  // 4 real pages under javadoc/next + the added mcp/index.html + 1 under javadoc/latest = 6;
  // the 2 redirect stubs are never counted, even though they are now minimally edited.
  assert.equal(updated, 6, 'redirect stubs must not be counted as updated pages');

  for (const relPath of ['overview-summary.html', 'mcp/overview-summary.html']) {
    const stub = readFileSync(join(surfaceRoot, ...relPath.split('/')), 'utf8');
    assert.equal(
      stub,
      REDIRECT_STUB_WITH_ROBOTS,
      `${relPath} must gain exactly the robots tag — plugin-authored canonical, title, refresh and body untouched`,
    );
    // Spelled out explicitly: the redirect behaviour this stub exists for must survive verbatim.
    assert.match(stub, /<link rel="canonical" href="index\.html">/);
    assert.match(stub, /window\.location\.replace\('index\.html'\)/);
    assert.match(stub, /<meta http-equiv="Refresh" content="0;index\.html">/);
  }
  // The nested sub-surface's REAL overview page (not the stub next to it) is still processed.
  const mcpIndex = readFileSync(join(surfaceRoot, 'mcp', 'index.html'), 'utf8');
  assert.match(mcpIndex, /<link rel="canonical" href="https:\/\/agentforge4j\.org\/javadoc\/next\/mcp\/index\.html">/);
});

test('a redirect stub under the noindexed mirrored version gains the robots tag too — the hole this closes was in the pinned tree, whose every other page is already noindexed', () => {
  const { siteDir, surfaceRoot } = fixtureSiteDirWithNestedPages('javadoc/0.1.0', ['0.1.0']);
  addRedirectStubs(surfaceRoot);
  const updated = applyJavadocSeo({
    siteDir,
    siteUrl: 'https://agentforge4j.org',
    ogImage: 'https://agentforge4j.org/brand/icon-512.png',
    releasedVersions: ['0.1.0'],
  });
  // 4 real pages under javadoc/0.1.0 + the added mcp/index.html + 1 each under next/latest = 7.
  assert.equal(updated, 7, 'redirect stubs must not be counted as updated pages');
  for (const relPath of ['overview-summary.html', 'mcp/overview-summary.html']) {
    const stub = readFileSync(join(surfaceRoot, ...relPath.split('/')), 'utf8');
    assert.equal(stub, REDIRECT_STUB_WITH_ROBOTS, `${relPath} must gain exactly the robots tag in a noindexed surface`);
  }
});

test('a redirect stub on an INDEXABLE surface (/latest/) is still left byte-identical — the robots injection is scoped to noindex surfaces, never applied blanket', () => {
  const { siteDir } = fixtureSiteDirWithNestedPages('javadoc/latest', ['0.1.0']);
  const latestRoot = join(siteDir, 'javadoc', 'latest');
  addRedirectStubs(latestRoot);
  applyJavadocSeo({
    siteDir,
    siteUrl: 'https://agentforge4j.org',
    ogImage: 'https://agentforge4j.org/brand/icon-512.png',
    releasedVersions: ['0.1.0'],
  });
  for (const relPath of ['overview-summary.html', 'mcp/overview-summary.html']) {
    const stub = readFileSync(join(latestRoot, ...relPath.split('/')), 'utf8');
    assert.equal(stub, RAW_REDIRECT_STUB_HTML, `${relPath} under indexable /latest/ must remain byte-identical`);
  }
});

test('addRobotsNoindexTag is idempotent by refusal — a stub processed twice never gains a second, potentially contradictory robots tag', () => {
  const once = addRobotsNoindexTag(RAW_REDIRECT_STUB_HTML);
  const twice = addRobotsNoindexTag(once);
  assert.equal(twice, once, 'a second pass must be a no-op');
  assert.equal((twice.match(/<meta name="robots"/g) ?? []).length, 1, 'exactly one robots tag');
});

test('page-relative canonical generation: a nested page canonicalizes to its own full relative path within the surface, never to the surface root or another surface', () => {
  const { siteDir } = fixtureSiteDirWithNestedPages('javadoc/latest');
  applyJavadocSeo({
    siteDir,
    siteUrl: 'https://agentforge4j.org',
    ogImage: 'https://agentforge4j.org/brand/icon-512.png',
    releasedVersions: [],
  });
  const classPage = readFileSync(join(siteDir, 'javadoc', 'latest', 'com', 'example', 'Foo.html'), 'utf8');
  assert.match(classPage, /<link rel="canonical" href="https:\/\/agentforge4j\.org\/javadoc\/latest\/com\/example\/Foo\.html">/);
  assert.doesNotMatch(classPage, /href="https:\/\/agentforge4j\.org\/javadoc\/latest\/"/, 'must not canonicalize to the surface root');
});

test('noindex,follow is applied to every page under the version currently mirrored by /latest/ — not only its overview', () => {
  const { siteDir } = fixtureSiteDirWithNestedPages('javadoc/0.1.0');
  applyJavadocSeo({
    siteDir,
    siteUrl: 'https://agentforge4j.org',
    ogImage: 'https://agentforge4j.org/brand/icon-512.png',
    releasedVersions: ['0.1.0'],
  });
  for (const relPath of ['index.html', 'allclasses-index.html', 'com/example/package-summary.html', 'com/example/Foo.html']) {
    const html = readFileSync(join(siteDir, 'javadoc', '0.1.0', ...relPath.split('/')), 'utf8');
    assert.match(html, /<meta name="robots" content="noindex,follow">/, `${relPath} must be noindex,follow (it duplicates /latest/)`);
  }
});

test('no robots tag appears anywhere under /javadoc/latest/** (always indexable, whole tree)', () => {
  const { siteDir } = fixtureSiteDirWithNestedPages('javadoc/latest');
  applyJavadocSeo({
    siteDir,
    siteUrl: 'https://agentforge4j.org',
    ogImage: 'https://agentforge4j.org/brand/icon-512.png',
    releasedVersions: [],
  });
  for (const relPath of ['index.html', 'allclasses-index.html', 'com/example/package-summary.html', 'com/example/Foo.html']) {
    const html = readFileSync(join(siteDir, 'javadoc', 'latest', ...relPath.split('/')), 'utf8');
    assert.doesNotMatch(html, /<meta name="robots"/, `${relPath} under /latest/ must never be noindexed`);
  }
});

test('once a newer version ships, the OLD newest version (no longer a duplicate of /latest/) becomes indexable again everywhere in its tree — no hardcoded version', () => {
  const siteDir = fixtureSiteDir(['javadoc/next', 'javadoc/latest', 'javadoc/0.1.0', 'javadoc/0.2.0']);
  applyJavadocSeo({
    siteDir,
    siteUrl: 'https://agentforge4j.org',
    ogImage: 'https://agentforge4j.org/brand/icon-512.png',
    // Newest-first, matching versions.json's own convention (and assembleSite's own latestSource pick).
    releasedVersions: ['0.2.0', '0.1.0'],
  });
  const nowOld = readFileSync(join(siteDir, 'javadoc', '0.1.0', 'index.html'), 'utf8');
  assert.doesNotMatch(nowOld, /<meta name="robots"/, '0.1.0 is no longer byte-identical to /latest/ once 0.2.0 exists — must not stay noindexed');

  const nowNewest = readFileSync(join(siteDir, 'javadoc', '0.2.0', 'index.html'), 'utf8');
  assert.match(nowNewest, /<meta name="robots" content="noindex,follow">/, '0.2.0 is now the version /latest/ mirrors');

  // /next/ stays noindex no matter how many releases exist — the suppression is unconditional, not
  // a pre-release special case.
  const next = readFileSync(join(siteDir, 'javadoc', 'next', 'index.html'), 'utf8');
  assert.match(next, /<meta name="robots" content="noindex,follow">/, '/next/ is noindex in every lifecycle state');
});

// --- the complete /next vs /latest duplicate-content lifecycle matrix ---------------------------
//
// Counts the exact number of `<meta name="robots"` occurrences rather than a loose substring check
// — a page with two robots tags (one noindex, one accidentally left indexable, say) must not be
// mistaken for correctly noindexed just because *a* match was found somewhere in the string.
function robotsTagCount(html) {
  return (html.match(/<meta name="robots"/g) ?? []).length;
}

function assertNoindexFollowExactlyOnce(html, label) {
  assert.equal(robotsTagCount(html), 1, `${label}: expected exactly one robots tag`);
  assert.match(html, /<meta name="robots" content="noindex,follow">/, `${label}: expected noindex,follow`);
}

function assertNoRobotsTag(html, label) {
  assert.equal(robotsTagCount(html), 0, `${label}: expected no robots tag at all (indexable)`);
}

test('lifecycle matrix — no released versions: /next/** is noindex,follow (exactly one tag, whole tree) and /latest/** is fully indexable (whole tree)', () => {
  const { siteDir } = fixtureSiteDirWithNestedPages('javadoc/next', []);
  applyJavadocSeo({
    siteDir,
    siteUrl: 'https://agentforge4j.org',
    ogImage: 'https://agentforge4j.org/brand/icon-512.png',
    releasedVersions: [],
  });
  for (const relPath of ['index.html', 'allclasses-index.html', 'com/example/package-summary.html', 'com/example/Foo.html']) {
    const nextHtml = readFileSync(join(siteDir, 'javadoc', 'next', ...relPath.split('/')), 'utf8');
    assertNoindexFollowExactlyOnce(nextHtml, `/next/${relPath} (pre-release — mirrors /latest/ byte-for-byte)`);
  }
  // /latest/ in this fixture is a plain overview-only surface (fixtureSiteDirWithNestedPages always
  // creates one for the surfaces not under test) — still enough to prove it stays indexable.
  const latestHtml = readFileSync(join(siteDir, 'javadoc', 'latest', 'index.html'), 'utf8');
  assertNoRobotsTag(latestHtml, '/latest/index.html (pre-release — the evergreen public entry point)');
});

test('lifecycle matrix — no released versions, checked from the /latest/ side too: full nested tree stays indexable while /next/ (built the same way) is suppressed', () => {
  const { siteDir } = fixtureSiteDirWithNestedPages('javadoc/latest', []);
  applyJavadocSeo({
    siteDir,
    siteUrl: 'https://agentforge4j.org',
    ogImage: 'https://agentforge4j.org/brand/icon-512.png',
    releasedVersions: [],
  });
  for (const relPath of ['index.html', 'allclasses-index.html', 'com/example/package-summary.html', 'com/example/Foo.html']) {
    const latestHtml = readFileSync(join(siteDir, 'javadoc', 'latest', ...relPath.split('/')), 'utf8');
    assertNoRobotsTag(latestHtml, `/latest/${relPath}`);
  }
  const nextHtml = readFileSync(join(siteDir, 'javadoc', 'next', 'index.html'), 'utf8');
  assertNoindexFollowExactlyOnce(nextHtml, '/next/index.html');
});

test('lifecycle matrix — first stable release: /latest/** stays indexable, /next/** stays noindex, the new release is noindex,follow', () => {
  const { siteDir } = fixtureSiteDirWithNestedPages('javadoc/0.1.0', ['0.1.0']);
  applyJavadocSeo({
    siteDir,
    siteUrl: 'https://agentforge4j.org',
    ogImage: 'https://agentforge4j.org/brand/icon-512.png',
    releasedVersions: ['0.1.0'],
  });
  // This is the exact state production runs in (versions.json === ["0.1.0"]). /next/ is built from
  // main and /latest/ from the 0.1.0 tag, so the two trees are byte-identical until main's public
  // API diverges — /next/ must not be a second indexable copy of /latest/ in this state.
  const next = readFileSync(join(siteDir, 'javadoc', 'next', 'index.html'), 'utf8');
  assertNoindexFollowExactlyOnce(next, '/next/ (byte-identical to /latest/ until main diverges)');

  const latest = readFileSync(join(siteDir, 'javadoc', 'latest', 'index.html'), 'utf8');
  assertNoRobotsTag(latest, '/latest/');

  for (const relPath of ['index.html', 'allclasses-index.html', 'com/example/package-summary.html', 'com/example/Foo.html']) {
    const pinned = readFileSync(join(siteDir, 'javadoc', '0.1.0', ...relPath.split('/')), 'utf8');
    assertNoindexFollowExactlyOnce(pinned, `/javadoc/0.1.0/${relPath}`);
  }
});

test('lifecycle matrix — newer stable release: the new version is noindex,follow, the old one is indexable again, /latest/ stays indexable and /next/ stays noindex', () => {
  const { siteDir } = fixtureSiteDirWithNestedPages('javadoc/0.2.0', ['0.2.0', '0.1.0']);
  // Also give 0.1.0 a real nested tree of its own, so its "becomes indexable again" transition is
  // proven across the whole surface, not only its overview.
  mkdirSync(join(siteDir, 'javadoc', '0.1.0', 'com', 'example'), { recursive: true });
  writeFileSync(join(siteDir, 'javadoc', '0.1.0', 'allclasses-index.html'), rawAllClassesIndexHtml(), 'utf8');
  writeFileSync(join(siteDir, 'javadoc', '0.1.0', 'com', 'example', 'package-summary.html'), rawPackageSummaryHtml(), 'utf8');
  writeFileSync(join(siteDir, 'javadoc', '0.1.0', 'com', 'example', 'Foo.html'), rawClassPageHtml(), 'utf8');

  applyJavadocSeo({
    siteDir,
    siteUrl: 'https://agentforge4j.org',
    ogImage: 'https://agentforge4j.org/brand/icon-512.png',
    releasedVersions: ['0.2.0', '0.1.0'],
  });

  for (const relPath of ['index.html', 'allclasses-index.html', 'com/example/package-summary.html', 'com/example/Foo.html']) {
    const newest = readFileSync(join(siteDir, 'javadoc', '0.2.0', ...relPath.split('/')), 'utf8');
    assertNoindexFollowExactlyOnce(newest, `/javadoc/0.2.0/${relPath}`);
    const old = readFileSync(join(siteDir, 'javadoc', '0.1.0', ...relPath.split('/')), 'utf8');
    assertNoRobotsTag(old, `/javadoc/0.1.0/${relPath} (no longer the version /latest/ mirrors)`);
  }
  const next = readFileSync(join(siteDir, 'javadoc', 'next', 'index.html'), 'utf8');
  assertNoindexFollowExactlyOnce(next, '/next/ (noindex in every lifecycle state)');
  const latest = readFileSync(join(siteDir, 'javadoc', 'latest', 'index.html'), 'utf8');
  assertNoRobotsTag(latest, '/latest/');
});

test('applyJavadocSeo processes the real surfaces.html landing page (build-javadoc.mjs\'s own hand-authored, description-less page) without throwing — this is the exact real-corpus defect a full-tree compose caught: surfaces.html is otherwise indistinguishable from a genuine template-drift page missing its description', () => {
  const { siteDir, surfaceRoot } = fixtureSiteDirWithNestedPages('javadoc/next');
  writeFileSync(join(surfaceRoot, 'surfaces.html'), RAW_SURFACES_LANDING_HTML, 'utf8');
  const updated = applyJavadocSeo({
    siteDir,
    siteUrl: 'https://agentforge4j.org',
    ogImage: 'https://agentforge4j.org/brand/icon-512.png',
    releasedVersions: [],
  });
  assert.equal(updated, 6, 'the 5 pages from the base nested fixture plus the new surfaces.html');
  const surfacesPage = readFileSync(join(surfaceRoot, 'surfaces.html'), 'utf8');
  assert.match(surfacesPage, /<meta name="description" content="[^"]+">/);
  assert.match(surfacesPage, /<link rel="canonical" href="https:\/\/agentforge4j\.org\/javadoc\/next\/surfaces\.html">/);
  // Same doc-title heading correction through the full applyJavadocSeo path; the hand-authored
  // body content survives.
  assert.match(surfacesPage, /<h1>AgentForge4j API — surfaces — AgentForge4j API Reference \(next, in-development\)<\/h1>/);
  assert.match(surfacesPage, /<li><a href="\.\/index\.html">Core API \(aggregate\)<\/a><\/li>/);
});

test('applyJavadocSeo names the offending file path when a genuinely description-less page is NOT the recognized surfaces.html landing page (template drift, still fails closed)', () => {
  const { siteDir, surfaceRoot } = fixtureSiteDirWithNestedPages('javadoc/next');
  // A description-less page under a different name must still fail loud — the error must name the
  // offending file, not just report a bare "template drift?" with no way to tell which of hundreds
  // of pages across three surfaces is the actual problem.
  writeFileSync(join(surfaceRoot, 'drifted-page.html'), RAW_SURFACES_LANDING_HTML, 'utf8');
  assert.throws(
    () =>
      applyJavadocSeo({
        siteDir,
        siteUrl: 'https://agentforge4j.org',
        ogImage: 'https://agentforge4j.org/brand/icon-512.png',
        releasedVersions: [],
      }),
    /failed processing .*drifted-page\.html.*expected a <meta name="description"/,
  );
});

test('a nested page\'s raw <title> containing HTML entities (e.g. a generic class like Foo<T>, which javadoc emits as Foo&lt;T&gt;) is decoded once and escaped exactly once — never double-escaped into literal "&lt;" text', () => {
  const { siteDir, surfaceRoot } = fixtureSiteDirWithNestedPages('javadoc/next');
  writeFileSync(
    join(surfaceRoot, 'com', 'example', 'Foo.html'),
    rawClassPageHtml({ title: withWindowTitle('Foo&lt;T&gt; &amp; Bar') }),
    'utf8',
  );
  applyJavadocSeo({
    siteDir,
    siteUrl: 'https://agentforge4j.org',
    ogImage: 'https://agentforge4j.org/brand/icon-512.png',
    releasedVersions: [],
  });
  const classPage = readFileSync(join(surfaceRoot, 'com', 'example', 'Foo.html'), 'utf8');
  // Semantically "Foo<T> & Bar" — escaped exactly once for HTML attribute embedding.
  assert.ok(
    classPage.includes(
      '<meta name="description" content="Generated Javadoc API reference for the AgentForge4j framework (next, in-development) — Foo&lt;T&gt; &amp; Bar.">',
    ),
  );
  assert.ok(
    classPage.includes(
      '<meta property="og:title" content="Foo&lt;T&gt; &amp; Bar — AgentForge4j API Reference (next, in-development)">',
    ),
  );
  assert.ok(!classPage.includes('&amp;lt;'), 'must never double-escape &lt; into &amp;lt; (renders as literal "&lt;" text)');
  assert.ok(!classPage.includes('&amp;gt;'), 'must never double-escape &gt; into &amp;gt;');
  assert.ok(!classPage.includes('&amp;amp;'), 'must never double-escape &amp; into &amp;amp;');
});

test('a nested page\'s raw <title> containing numeric character references and &nbsp; (e.g. an annotation type like @Foo, which javadoc emits as &#64;Foo) is decoded to the real character, not left as literal entity text', () => {
  const { siteDir, surfaceRoot } = fixtureSiteDirWithNestedPages('javadoc/next');
  writeFileSync(
    join(surfaceRoot, 'com', 'example', 'Foo.html'),
    rawClassPageHtml({ title: withWindowTitle('&#64;Foo&nbsp;Bar &#x2019;s') }),
    'utf8',
  );
  applyJavadocSeo({
    siteDir,
    siteUrl: 'https://agentforge4j.org',
    ogImage: 'https://agentforge4j.org/brand/icon-512.png',
    releasedVersions: [],
  });
  const classPage = readFileSync(join(surfaceRoot, 'com', 'example', 'Foo.html'), 'utf8');
  // &nbsp; decodes to the real U+00A0 character (consistent with every other entity here decoding
  // to its real character), not a plain space — hence the literal U+00A0 between "Foo" and "Bar".
  const ogTitleLine = classPage.split(/\r?\n/).find((line) => line.includes('property="og:title"'));
  assert.equal(
    ogTitleLine.trim(),
    '<meta property="og:title" content="@Foo Bar ’s — AgentForge4j API Reference (next, in-development)">',
  );
  // The original, unmodified <title> element legitimately still carries the raw entities — only the
  // derived meta tags (og:title checked below; description/twitter share the same decoded pageTitle)
  // must never carry them.
  assert.ok(!ogTitleLine.includes('&#64;'), 'must not leave a decimal numeric character reference as literal entity text');
  assert.ok(!ogTitleLine.includes('&#x2019;'), 'must not leave a hex numeric character reference as literal entity text');
  assert.ok(!ogTitleLine.includes('&nbsp;'), 'must not leave &nbsp; as literal entity text');
});

test('entity decoding is a single pass — a raw title spelling out a literal "&amp;" via &#38;amp; is never double-decoded into a bare "&"', () => {
  const { siteDir, surfaceRoot } = fixtureSiteDirWithNestedPages('javadoc/next');
  writeFileSync(
    join(surfaceRoot, 'com', 'example', 'Foo.html'),
    // Source intent: the displayed title text is `A &amp; B` — the leading &#38; IS the ampersand,
    // and the `amp;` after it is plain text. One decode pass yields exactly that; a sequential
    // decode chain would rescan its own output and collapse the whole thing to `A & B`.
    rawClassPageHtml({ title: withWindowTitle('A &#38;amp; B') }),
    'utf8',
  );
  applyJavadocSeo({
    siteDir,
    siteUrl: 'https://agentforge4j.org',
    ogImage: 'https://agentforge4j.org/brand/icon-512.png',
    releasedVersions: [],
  });
  const classPage = readFileSync(join(surfaceRoot, 'com', 'example', 'Foo.html'), 'utf8');
  const ogTitleLine = classPage.split(/\r?\n/).find((line) => line.includes('property="og:title"'));
  // Decoded text `A &amp; B` (6 literal chars in the middle), then escaped exactly once for the
  // attribute: the literal `&` re-encodes to `&amp;`, so the attribute reads `A &amp;amp; B`.
  assert.equal(
    ogTitleLine.trim(),
    '<meta property="og:title" content="A &amp;amp; B — AgentForge4j API Reference (next, in-development)">',
  );
});

test('fails closed when a declared surface\'s overview page is missing', () => {
  const siteDir = fixtureSiteDir(['javadoc/next', 'javadoc/latest']); // 0.1.0 missing entirely
  assert.throws(
    () =>
      applyJavadocSeo({
        siteDir,
        siteUrl: 'https://agentforge4j.org',
        ogImage: 'https://agentforge4j.org/brand/icon-512.png',
        releasedVersions: ['0.1.0'],
      }),
    /expected surface overview page missing/,
  );
});

test('non-HTML assets (stylesheet.css) remain byte-identical after processing', () => {
  const { siteDir } = fixtureSiteDirWithNestedPages('javadoc/next');
  const before = readFileSync(join(siteDir, 'javadoc', 'next', 'stylesheet.css'), 'utf8');
  applyJavadocSeo({
    siteDir,
    siteUrl: 'https://agentforge4j.org',
    ogImage: 'https://agentforge4j.org/brand/icon-512.png',
    releasedVersions: [],
  });
  const after = readFileSync(join(siteDir, 'javadoc', 'next', 'stylesheet.css'), 'utf8');
  assert.equal(after, before);
});

test('nested Javadoc navigation/body content remains intact after processing (class page markup, real generated member signature)', () => {
  const { siteDir } = fixtureSiteDirWithNestedPages('javadoc/next');
  applyJavadocSeo({
    siteDir,
    siteUrl: 'https://agentforge4j.org',
    ogImage: 'https://agentforge4j.org/brand/icon-512.png',
    releasedVersions: [],
  });
  const classPage = readFileSync(join(siteDir, 'javadoc', 'next', 'com', 'example', 'Foo.html'), 'utf8');
  assert.match(classPage, /<h1 class="title">Class Foo<\/h1>/);
  assert.match(classPage, /public class <span class="element-name">Foo<\/span>/);
});

test('a full fixture tree reports the exact number of processed HTML pages (4 real pages under javadoc/next — overview, all-classes index, package summary, class page — plus 1 plain overview under javadoc/latest, always processed alongside it)', () => {
  const { siteDir } = fixtureSiteDirWithNestedPages('javadoc/next');
  const updated = applyJavadocSeo({
    siteDir,
    siteUrl: 'https://agentforge4j.org',
    ogImage: 'https://agentforge4j.org/brand/icon-512.png',
    releasedVersions: [],
  });
  assert.equal(updated, 5);
});

// --- isWithinRoot: the containment rule a symlinked directory/file's resolved target must satisfy
// before this module will follow it — directly testable without creating a real symlink (which
// requires elevated privileges on Windows, an environment concern this logic must not depend on to
// be verifiable) ---

test('isWithinRoot: a real descendant path is within root', () => {
  const root = join(tmpdir(), 'javadoc-root');
  assert.ok(isWithinRoot(root, join(root, 'com', 'example', 'Foo.html')));
  assert.ok(isWithinRoot(root, root));
});

test('isWithinRoot: a path reached via `..` traversal, or an unrelated sibling directory sharing the same string prefix, is rejected', () => {
  const root = join(tmpdir(), 'javadoc-root');
  assert.ok(!isWithinRoot(root, join(tmpdir(), 'secret.txt')));
  assert.ok(!isWithinRoot(root, join(tmpdir(), 'javadoc-root-evil', 'secret.txt')));
});

test('a symlinked directory pointing outside the surface root is refused, not silently followed (skipped in environments where creating a symlink requires elevated privileges, e.g. unconfigured Windows)', () => {
  const root = mkdtempSync(join(tmpdir(), 'javadoc-symlink-'));
  const siteDir = join(root, '_site');
  const surfaceRoot = join(siteDir, 'javadoc', 'next');
  mkdirSync(surfaceRoot, { recursive: true });
  writeFileSync(join(surfaceRoot, 'index.html'), RAW_OVERVIEW_HTML, 'utf8');
  const outsideDir = join(root, 'outside-the-surface');
  mkdirSync(outsideDir, { recursive: true });
  writeFileSync(join(outsideDir, 'secret.html'), RAW_OVERVIEW_HTML, 'utf8');

  let symlinkCreated = true;
  try {
    // 'junction' (not 'dir'): NTFS junctions don't require elevated privileges on Windows the way
    // true symbolic links do, so this test actually exercises the real containment check locally
    // instead of silently skipping — Node reports a junction identically to a symlink via
    // Dirent.isSymbolicLink(), so the code path under test is exactly the same either way.
    symlinkSync(outsideDir, join(surfaceRoot, 'escape'), 'junction');
  } catch (error) {
    if (error.code === 'EPERM' || error.code === 'EACCES') {
      symlinkCreated = false;
    } else {
      throw error;
    }
  }
  if (!symlinkCreated) {
    console.log('[javadoc-seo.test] symlink creation requires elevated privileges in this environment — skipping the live symlink assertion (isWithinRoot itself is covered by the two tests above)');
    return;
  }

  assert.throws(
    () =>
      applyJavadocSeo({
        siteDir,
        siteUrl: 'https://agentforge4j.org',
        ogImage: 'https://agentforge4j.org/brand/icon-512.png',
        releasedVersions: [],
      }),
    /refusing to follow a symlink that escapes the surface root/,
  );
});

test('a surface root reached only via a symlinked ancestor path still processes normally, with no in-root symlink involved (skipped where symlink creation requires elevated privileges, e.g. unconfigured Windows)', () => {
  const root = mkdtempSync(join(tmpdir(), 'javadoc-symlinked-ancestor-'));
  const realRoot = join(root, 'real');
  const siteDirReal = join(realRoot, '_site');
  for (const mountPath of ['javadoc/next', 'javadoc/latest']) {
    const dir = join(siteDirReal, ...mountPath.split('/'));
    mkdirSync(dir, { recursive: true });
    writeFileSync(join(dir, 'index.html'), RAW_OVERVIEW_HTML, 'utf8');
  }
  const nextSurfaceRoot = join(siteDirReal, 'javadoc', 'next');
  writeFileSync(join(nextSurfaceRoot, 'Foo.html'), rawClassPageHtml(), 'utf8');

  const aliasedRoot = join(root, 'aliased');
  let symlinkCreated = true;
  try {
    // 'junction': see the note on the escape-root test above.
    symlinkSync(realRoot, aliasedRoot, 'junction');
  } catch (error) {
    if (error.code === 'EPERM' || error.code === 'EACCES') {
      symlinkCreated = false;
    } else {
      throw error;
    }
  }
  if (!symlinkCreated) {
    console.log('[javadoc-seo.test] symlink creation requires elevated privileges in this environment — skipping the live symlinked-ancestor assertion (isWithinRoot itself is covered by the tests above)');
    return;
  }

  const siteDir = join(aliasedRoot, '_site');
  // Must NOT throw: every real file under the surface resolves inside the real surface root, and
  // that root is itself only reachable here via the symlinked `aliased` ancestor path — comparing
  // a realpath'd symlink target against the unresolved `root` would spuriously fail the first
  // symlink this walk ever encountered (there are none here — this proves ancestor resolution in
  // isolation, with no in-root symlink of its own).
  const updated = applyJavadocSeo({
    siteDir,
    siteUrl: 'https://agentforge4j.org',
    ogImage: 'https://agentforge4j.org/brand/icon-512.png',
    releasedVersions: [],
  });
  assert.equal(updated, 3, 'next: index + Foo (2), latest: index (1)');
});

// --- an in-root symlink can create two distinct walked paths that resolve to the SAME underlying
// real file or directory — walkHtmlFiles must refuse this outright rather than silently
// double-processing a page or recursing forever. ---

test('a symlinked HTML file is refused outright — ambiguous which of the two paths is the page\'s one real canonical URL (skipped where symlink creation requires elevated privileges)', () => {
  const { siteDir, surfaceRoot } = fixtureSiteDirWithNestedPages('javadoc/next');
  let symlinkCreated = true;
  try {
    symlinkSync(join(surfaceRoot, 'com', 'example', 'Foo.html'), join(surfaceRoot, 'Foo-alias.html'), 'file');
  } catch (error) {
    if (error.code === 'EPERM' || error.code === 'EACCES') {
      symlinkCreated = false;
    } else {
      throw error;
    }
  }
  if (!symlinkCreated) {
    console.log('[javadoc-seo.test] symlink creation requires elevated privileges in this environment — skipping');
    return;
  }
  assert.throws(
    () =>
      applyJavadocSeo({
        siteDir,
        siteUrl: 'https://agentforge4j.org',
        ogImage: 'https://agentforge4j.org/brand/icon-512.png',
        releasedVersions: [],
      }),
    /refusing to follow a symlinked HTML file \(ambiguous canonical URL\)/,
  );
});

test('a directory symlink pointing back at an ancestor (a cycle) is refused, not walked forever (skipped where symlink creation requires elevated privileges)', () => {
  const { siteDir, surfaceRoot } = fixtureSiteDirWithNestedPages('javadoc/next');
  let symlinkCreated = true;
  try {
    // com/example/back-to-root -> the surface root itself: walking into it would revisit `com`,
    // `com/example`, and `com/example/back-to-root` forever without cycle detection. 'junction':
    // see the note on the escape-root test above — runs for real locally, not just in CI.
    symlinkSync(surfaceRoot, join(surfaceRoot, 'com', 'example', 'back-to-root'), 'junction');
  } catch (error) {
    if (error.code === 'EPERM' || error.code === 'EACCES') {
      symlinkCreated = false;
    } else {
      throw error;
    }
  }
  if (!symlinkCreated) {
    console.log('[javadoc-seo.test] symlink creation requires elevated privileges in this environment — skipping');
    return;
  }
  assert.throws(
    () =>
      applyJavadocSeo({
        siteDir,
        siteUrl: 'https://agentforge4j.org',
        ogImage: 'https://agentforge4j.org/brand/icon-512.png',
        releasedVersions: [],
      }),
    /refusing to walk a directory whose real path was already visited/,
  );
});

test('two directory paths resolving to the same real directory (a real subtree plus a symlinked alias of it) are refused, not silently double-processed (skipped where symlink creation requires elevated privileges)', () => {
  const { siteDir, surfaceRoot } = fixtureSiteDirWithNestedPages('javadoc/next');
  let symlinkCreated = true;
  try {
    // "alias" is a second, independent path to the exact same real directory as com/example.
    // 'junction': see the note on the escape-root test above.
    symlinkSync(join(surfaceRoot, 'com', 'example'), join(surfaceRoot, 'alias'), 'junction');
  } catch (error) {
    if (error.code === 'EPERM' || error.code === 'EACCES') {
      symlinkCreated = false;
    } else {
      throw error;
    }
  }
  if (!symlinkCreated) {
    console.log('[javadoc-seo.test] symlink creation requires elevated privileges in this environment — skipping');
    return;
  }
  assert.throws(
    () =>
      applyJavadocSeo({
        siteDir,
        siteUrl: 'https://agentforge4j.org',
        ogImage: 'https://agentforge4j.org/brand/icon-512.png',
        releasedVersions: [],
      }),
    /refusing to walk a directory whose real path was already visited/,
  );
});

// --- generated window-title correction ----------------------------------------------------------
//
// maven-javadoc-plugin bakes the configured `-windowtitle` into every page's `<title>` at GENERATION
// time. That value is a single fixed string (`AgentForge4j API (next)` — agentforge4j-docs-javadoc/
// pom.xml), and /latest/ and every version-pinned tree are copies of a surface built from a release
// tag by that tag's own build, so without correction every page of every surface is titled `next` —
// including the stable API reference that is the one tree meant to be found in search.

test('stripJavadocWindowTitle removes the generated window-title suffix from every real page-kind title shape', () => {
  assert.equal(stripJavadocWindowTitle('Overview (AgentForge4j API (next))'), 'Overview');
  assert.equal(stripJavadocWindowTitle('agentforge4j.core (AgentForge4j API (next))'), 'agentforge4j.core');
  assert.equal(stripJavadocWindowTitle('com.agentforge4j.util (AgentForge4j API (next))'), 'com.agentforge4j.util');
  assert.equal(stripJavadocWindowTitle('Index (AgentForge4j API (next))'), 'Index');
  assert.equal(stripJavadocWindowTitle('Class Hierarchy (AgentForge4j API (next))'), 'Class Hierarchy');
  assert.equal(stripJavadocWindowTitle('All Classes and Interfaces (AgentForge4j API (next))'), 'All Classes and Interfaces');
});

test('stripJavadocWindowTitle keeps working if the pom drops the (next) suffix, or carries a version, in the window title', () => {
  assert.equal(stripJavadocWindowTitle('Overview (AgentForge4j API)'), 'Overview');
  // A brand-prefixed window title carrying a version is the plugin-default shape and IS stripped —
  // matching only the literal `AgentForge4j API` was the defect, not the intent.
  assert.equal(stripJavadocWindowTitle('Foo (AgentForge4j API 1.0)'), 'Foo');
});

test('stripJavadocWindowTitle is conservative — a page title that legitimately ends in parentheses is never eaten', () => {
  assert.equal(stripJavadocWindowTitle('Foo'), 'Foo');
  assert.equal(stripJavadocWindowTitle('Foo (deprecated)'), 'Foo (deprecated)');
  assert.equal(stripJavadocWindowTitle('SomeClass (Some Other Library)'), 'SomeClass (Some Other Library)');
  // The stub's title IS the bare window title — nothing page-specific to keep, so it is left alone
  // rather than being reduced to an empty string.
  assert.equal(stripJavadocWindowTitle('AgentForge4j API (next)'), 'AgentForge4j API (next)');
});

test('the rendered <title> is rewritten to the lifecycle-correct text, never left as maven-javadoc-plugin generated it', () => {
  const html = injectJavadocPageSeo(RAW_OVERVIEW_HTML, {
    title: 'AgentForge4j API Reference — latest stable, 0.1.0',
    description: 'Generated Javadoc API reference for the AgentForge4j framework (latest stable, 0.1.0).',
    canonical: 'https://agentforge4j.org/javadoc/latest/',
    ogImage: 'https://agentforge4j.org/brand/icon-512.png',
  });
  assert.match(html, /<title>AgentForge4j API Reference — latest stable, 0\.1\.0<\/title>/);
  assert.doesNotMatch(html, /<title>Overview \(AgentForge4j API \(next\)\)<\/title>/);
});

test('injectJavadocPageSeo fails closed on a page with no <title> at all (template drift)', () => {
  assert.throws(
    () =>
      injectJavadocPageSeo('<!DOCTYPE HTML>\n<html lang="en">\n<head>\n<meta name="description" content="x">\n</head>\n<body></body>\n</html>', {
        title: 'T',
        description: 'D',
        canonical: 'https://agentforge4j.org/javadoc/latest/',
        ogImage: 'https://agentforge4j.org/brand/icon-512.png',
      }),
    /expected a <title> tag/,
  );
});

test('no page of ANY lifecycle tree is labelled "(next)" unless it really is /next/ — title, description and og:title together, across the whole nested corpus', () => {
  const { siteDir } = fixtureSiteDirWithNestedPages('javadoc/0.1.0', ['0.1.0']);
  applyJavadocSeo({
    siteDir,
    siteUrl: 'https://agentforge4j.org',
    ogImage: 'https://agentforge4j.org/brand/icon-512.png',
    releasedVersions: ['0.1.0'],
  });

  const pages = ['index.html', 'allclasses-index.html', 'com/example/package-summary.html', 'com/example/Foo.html'];

  // The pinned tree carries its own version label and must never mention the generator's `next`.
  for (const relPath of pages) {
    const html = readFileSync(join(siteDir, 'javadoc', '0.1.0', ...relPath.split('/')), 'utf8');
    assert.doesNotMatch(
      html,
      /AgentForge4j API \(next\)/,
      `/javadoc/0.1.0/${relPath}: the generated window title must not survive anywhere in the head`,
    );
    assert.match(
      html,
      /<title>[^<]*(?:\(0\.1\.0\)|— 0\.1\.0)<\/title>/,
      `/javadoc/0.1.0/${relPath}: <title> must carry its own version label`,
    );
    assert.match(
      html,
      /<meta property="og:title" content="[^"]*(?:\(0\.1\.0\)|— 0\.1\.0)">/,
      `/javadoc/0.1.0/${relPath}: og:title must carry its own version label`,
    );
    assert.match(
      html,
      /<meta name="description" content="[^"]*\(0\.1\.0\)[^"]*">/,
      `/javadoc/0.1.0/${relPath}: description must carry its own version label`,
    );
  }

  // /latest/ — the one indexable tree, and the one the mislabelling hurt most.
  const latest = readFileSync(join(siteDir, 'javadoc', 'latest', 'index.html'), 'utf8');
  assert.doesNotMatch(latest, /AgentForge4j API \(next\)/, '/latest/ must never be labelled next');
  assert.match(latest, /<title>AgentForge4j API Reference — latest stable, 0\.1\.0<\/title>/);

  // /next/ genuinely IS next — it keeps its own honest label, which is not the generator's suffix.
  const next = readFileSync(join(siteDir, 'javadoc', 'next', 'index.html'), 'utf8');
  assert.match(next, /<title>AgentForge4j API Reference — next, in-development<\/title>/);
  assert.doesNotMatch(next, /AgentForge4j API \(next\)/, 'even /next/ must not carry the raw generated window title');
});

test('a nested page keeps its own page-specific title text after the window-title suffix is stripped — the label is added, the identity is not lost', () => {
  const { siteDir } = fixtureSiteDirWithNestedPages('javadoc/latest', ['0.1.0']);
  applyJavadocSeo({
    siteDir,
    siteUrl: 'https://agentforge4j.org',
    ogImage: 'https://agentforge4j.org/brand/icon-512.png',
    releasedVersions: ['0.1.0'],
  });
  const classPage = readFileSync(join(siteDir, 'javadoc', 'latest', 'com', 'example', 'Foo.html'), 'utf8');
  assert.match(classPage, /<title>Foo — AgentForge4j API Reference \(latest stable, 0\.1\.0\)<\/title>/);
  const packageSummary = readFileSync(join(siteDir, 'javadoc', 'latest', 'com', 'example', 'package-summary.html'), 'utf8');
  assert.match(packageSummary, /<title>com\.example — AgentForge4j API Reference \(latest stable, 0\.1\.0\)<\/title>/);
});

test('the visible overview <h1> (maven-javadoc-plugin renders the doc title there) is corrected too — the rendered heading and the metadata agree', () => {
  const html = injectJavadocPageSeo(RAW_OVERVIEW_HTML, {
    title: 'AgentForge4j API Reference — latest stable, 0.1.0',
    description: 'd',
    canonical: 'https://agentforge4j.org/javadoc/latest/',
    ogImage: 'https://agentforge4j.org/brand/icon-512.png',
  });
  assert.match(html, /<h1 class="title">AgentForge4j API Reference — latest stable, 0\.1\.0<\/h1>/);
  assert.doesNotMatch(html, /AgentForge4j API \(next\)/, 'the raw doc title must not survive anywhere on the page');
});

test('the hand-authored surfaces.html landing page\'s own <h1> is corrected on the same rule', () => {
  const html = injectJavadocPageSeo(RAW_SURFACES_LANDING_HTML, {
    title: 'AgentForge4j API Reference — latest stable, 0.1.0',
    description: 'd',
    canonical: 'https://agentforge4j.org/javadoc/latest/surfaces.html',
    ogImage: 'https://agentforge4j.org/brand/icon-512.png',
    allowMissingDescription: true,
  });
  assert.match(html, /<h1>AgentForge4j API Reference — latest stable, 0\.1\.0<\/h1>/);
});

test('a real page heading is never rewritten by the doc-title heading correction — only a heading that IS the brand doc title', () => {
  const classPage = injectJavadocPageSeo(rawClassPageHtml(), {
    title: 'Foo — AgentForge4j API Reference (latest stable, 0.1.0)',
    description: 'd',
    canonical: 'https://agentforge4j.org/javadoc/latest/com/example/Foo.html',
    ogImage: 'https://agentforge4j.org/brand/icon-512.png',
  });
  assert.match(classPage, /<h1 class="title">Class Foo<\/h1>/, 'a real class heading must survive untouched');
  const allClasses = injectJavadocPageSeo(rawAllClassesIndexHtml(), {
    title: 'All Classes and Interfaces — AgentForge4j API Reference (latest stable, 0.1.0)',
    description: 'd',
    canonical: 'https://agentforge4j.org/javadoc/latest/allclasses-index.html',
    ogImage: 'https://agentforge4j.org/brand/icon-512.png',
  });
  assert.match(allClasses, /<h1 class="title">All Classes and Interfaces<\/h1>/);
});

// --- generator-variant coverage -----------------------------------------------------------------
//
// build-javadoc.mjs stitches THREE surfaces produced by TWO different Maven configurations: the
// aggregate (javadoc:aggregate, explicit pom <windowtitle> "AgentForge4j API (next)") and the two
// intentionally-unnamed modules (javadoc:javadoc with NO windowtitle, so maven-javadoc-plugin's own
// `${project.name} ${project.version} API` default applies — note the capital J in the project
// name). Modelling only the aggregate left ~95 pages per tree carrying a stale window title.
const MCP_WINDOW_TITLE = 'AgentForge4J MCP 0.1.0 API';
const STARTER_WINDOW_TITLE = 'AgentForge4J Spring Boot Starter 0.1.0 API';

test('stripJavadocWindowTitle handles the plugin-default window title of BOTH standalone sub-surfaces, not only the aggregate', () => {
  assert.equal(stripJavadocWindowTitle(`Overview (${MCP_WINDOW_TITLE})`), 'Overview');
  assert.equal(stripJavadocWindowTitle(`All Classes and Interfaces (${MCP_WINDOW_TITLE})`), 'All Classes and Interfaces');
  assert.equal(
    stripJavadocWindowTitle(`Uses of Class com.agentforge4j.mcp.client.McpServerConnection (${MCP_WINDOW_TITLE})`),
    'Uses of Class com.agentforge4j.mcp.client.McpServerConnection',
  );
  assert.equal(stripJavadocWindowTitle(`AgentForge4jProperties (${STARTER_WINDOW_TITLE})`), 'AgentForge4jProperties');
  assert.equal(stripJavadocWindowTitle(`All Packages (${STARTER_WINDOW_TITLE})`), 'All Packages');
  // A future release bumps the version — the shape, not the literal string, is what is matched.
  assert.equal(stripJavadocWindowTitle('Foo (AgentForge4J MCP 2.5.0-SNAPSHOT API)'), 'Foo');
});

test('stripJavadocWindowTitle stays conservative against the plugin-default shape too', () => {
  assert.equal(stripJavadocWindowTitle('Foo (deprecated)'), 'Foo (deprecated)');
  assert.equal(stripJavadocWindowTitle('SomeClass (Some Other Library 1.0 API)'), 'SomeClass (Some Other Library 1.0 API)');
  // The sub-surface stub's title IS the bare window title — nothing page-specific to keep.
  assert.equal(stripJavadocWindowTitle(MCP_WINDOW_TITLE), MCP_WINDOW_TITLE);
});

test('a sub-surface page generated with the plugin-default window title is fully normalised — title, og:title and description all carry the mount label and no residual window title', () => {
  const raw = rawClassPageHtml({ title: `AgentForge4jProperties (${STARTER_WINDOW_TITLE})` });
  // Composed the same way applyJavadocSeo's own nestedPageCopy does: strip the generated window
  // title from the page's raw <title>, then apply the mount's lifecycle label.
  const pageTitle = stripJavadocWindowTitle(`AgentForge4jProperties (${STARTER_WINDOW_TITLE})`);
  const html = injectJavadocPageSeo(raw, {
    title: `${pageTitle} — AgentForge4j API Reference (latest stable, 0.1.0)`,
    description: `Generated Javadoc API reference for the AgentForge4j framework (latest stable, 0.1.0) — ${pageTitle}.`,
    canonical: 'https://agentforge4j.org/javadoc/latest/spring-boot-starter/com/agentforge4j/starter/AgentForge4jProperties.html',
    ogImage: 'https://agentforge4j.org/brand/icon-512.png',
  });
  assert.match(html, /<title>AgentForge4jProperties — AgentForge4j API Reference \(latest stable, 0\.1\.0\)<\/title>/);
  assert.match(html, /<meta property="og:title" content="AgentForge4jProperties — AgentForge4j API Reference \(latest stable, 0\.1\.0\)">/);
  assert.doesNotMatch(html, /Spring Boot Starter 0\.1\.0 API/, 'the plugin-default window title must not survive anywhere');
});

test('a sub-surface overview <h1> carrying the plugin-default doc title is corrected too', () => {
  const rawOverview =
    '<!DOCTYPE HTML>\n<html lang>\n<head>\n' +
    `<title>Overview (${MCP_WINDOW_TITLE})</title>\n` +
    '<meta name="description" content="module index">\n' +
    '<meta name="generator" content="javadoc/ModuleIndexWriter">\n</head>\n' +
    `<body class="module-index-page"><div class="header"><h1 class="title">${MCP_WINDOW_TITLE}</h1></div></body>\n</html>\n`;
  const html = injectJavadocPageSeo(rawOverview, {
    title: 'AgentForge4j API Reference — latest stable, 0.1.0',
    description: 'd',
    canonical: 'https://agentforge4j.org/javadoc/latest/mcp/index.html',
    ogImage: 'https://agentforge4j.org/brand/icon-512.png',
  });
  assert.match(html, /<h1 class="title">AgentForge4j API Reference — latest stable, 0\.1\.0<\/h1>/);
  assert.doesNotMatch(html, /AgentForge4J MCP 0\.1\.0 API/, 'the plugin-default doc title must not survive in the heading');
});

test('a real class heading is still never rewritten under the widened heading rule', () => {
  for (const heading of ['Class Foo', 'Package com.example', 'Module agentforge4j.core', 'All Classes and Interfaces']) {
    const raw = rawClassPageHtml().replace('<h1 class="title">Class Foo</h1>', `<h1 class="title">${heading}</h1>`);
    const html = injectJavadocPageSeo(raw, {
      title: 'T', description: 'd',
      canonical: 'https://agentforge4j.org/javadoc/latest/com/example/Foo.html',
      ogImage: 'x',
    });
    assert.match(html, new RegExp(`<h1 class="title">${heading}</h1>`), `"${heading}" must survive untouched`);
  }
});

// --- robots-directive conflict ------------------------------------------------------------------

test('addRobotsNoindexTag refuses a stub that already carries a NON-noindex robots directive, rather than leaving it indexable on a suppressed surface', () => {
  const conflicting = RAW_REDIRECT_STUB_HTML.replace(
    '</head>',
    '<meta name="robots" content="index,follow">\n</head>',
  );
  assert.throws(() => addRobotsNoindexTag(conflicting), /conflicting robots directive \("index,follow"\)/);
});

test('addRobotsNoindexTag accepts an existing directive that already achieves noindex (idempotent), including a richer one', () => {
  for (const directive of ['noindex,follow', 'noindex', 'noindex, nofollow', 'NOINDEX,FOLLOW']) {
    const already = RAW_REDIRECT_STUB_HTML.replace('</head>', `<meta name="robots" content="${directive}">\n</head>`);
    assert.equal(addRobotsNoindexTag(already), already, `"${directive}" already suppresses — must be left untouched`);
  }
});

test('addRobotsNoindexTag fails closed on an unrecognized robots tag shape rather than adding a second one', () => {
  const oddShape = RAW_REDIRECT_STUB_HTML.replace('</head>', "<meta content='index' name=\"robots\">\n</head>");
  assert.throws(() => addRobotsNoindexTag(oddShape), /unrecognized robots tag shape/);
});

test('a malformed redirect stub names the file that failed, exactly like an ordinary page does', () => {
  const { siteDir, surfaceRoot } = fixtureSiteDirWithNestedPages('javadoc/next', []);
  // A stub recognized by its generator tag but with no </head> at all.
  writeFileSync(
    join(surfaceRoot, 'overview-summary.html'),
    '<!DOCTYPE HTML>\n<html lang>\n<meta name="generator" content="javadoc/IndexRedirectWriter">\n<body></body>\n</html>\n',
    'utf8',
  );
  assert.throws(
    () => applyJavadocSeo({
      siteDir, siteUrl: 'https://agentforge4j.org',
      ogImage: 'https://agentforge4j.org/brand/icon-512.png', releasedVersions: [],
    }),
    /failed processing .*overview-summary\.html/,
  );
});
