// SPDX-License-Identifier: Apache-2.0
//
// Navigation gate (enforceable at build time): every doc page must be reachable from a
// sidebar. The sidebar wires each Diátaxis/structural group via an `autogenerated`
// directory; this lint asserts that every Markdown/MDX page either is the explicit
// top-level entry or lives under one of those wired directories — so a page added
// outside the wired structure (orphan) fails the build instead of silently vanishing.
// It also flags wired directories / explicit ids that do not resolve to a file.

import {existsSync, readdirSync, readFileSync, statSync} from 'node:fs';
import {join, relative, sep, dirname} from 'node:path';
import {fileURLToPath} from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const ROOT = join(here, '..');
const DOCS_DIR = join(ROOT, 'docs');
const SIDEBARS = join(ROOT, 'sidebars.ts');
const DOC_EXTENSIONS = ['.md', '.mdx'];

function collectDocs(dir) {
  const out = [];
  for (const entry of readdirSync(dir)) {
    const full = join(dir, entry);
    if (statSync(full).isDirectory()) {
      out.push(...collectDocs(full));
    } else if (DOC_EXTENSIONS.some((ext) => entry.endsWith(ext))) {
      out.push(full);
    }
  }
  return out;
}

/** Strip the doc extension to get the path-form id. */
function toDocPath(file) {
  const rel = relative(DOCS_DIR, file).split(sep).join('/');
  return rel.replace(/\.(md|mdx)$/, '');
}

const sidebarSource = readFileSync(SIDEBARS, 'utf8');
const dirNames = [...sidebarSource.matchAll(/dirName:\s*['"]([^'"]+)['"]/g)].map((m) => m[1]);
const explicitIds = [...sidebarSource.matchAll(/\bid:\s*['"]([^'"]+)['"]/g)].map((m) => m[1]);

let violations = 0;

// 1. Every wired directory must exist.
for (const dir of dirNames) {
  if (!existsSync(join(DOCS_DIR, dir)) || !statSync(join(DOCS_DIR, dir)).isDirectory()) {
    console.error(`✗ sidebar wires dirName '${dir}' but docs/${dir}/ does not exist`);
    violations += 1;
  }
}

// 2. Every explicit doc id must resolve to a file.
for (const id of explicitIds) {
  const resolved = DOC_EXTENSIONS.some((ext) => existsSync(join(DOCS_DIR, id + ext)));
  if (!resolved) {
    console.error(`✗ sidebar references doc id '${id}' but no docs/${id}.{md,mdx} exists`);
    violations += 1;
  }
}

// 3. Every doc page must be covered by an explicit id or a wired directory.
const docs = collectDocs(DOCS_DIR);
for (const file of docs) {
  const docPath = toDocPath(file);
  const covered =
    explicitIds.includes(docPath) ||
    dirNames.some((d) => docPath === d || docPath.startsWith(d + '/'));
  if (!covered) {
    console.error(`✗ docs/${docPath} is not reachable from any sidebar group`);
    violations += 1;
  }
}

if (violations > 0) {
  console.error(`\nnav-lint: ${violations} violation(s) across ${docs.length} page(s).`);
  process.exit(1);
}

console.log(`nav-lint: ${docs.length} page(s) reachable; ${dirNames.length} wired group(s) OK.`);
