// SPDX-License-Identifier: Apache-2.0
package com.agentforge4j.llm.openai.dto;

import java.util.List;

/**
 * Response body for OpenAI-style {@code /v1/chat/completions} APIs.
 *
 * @param error   the error details if the request failed, or {@code null} if successful
 * @param choices the completion choices generated by the model
 */
public record OpenAiChatCompletionResponseDto(
  OpenAiErrorDto error,
  List<OpenAiChatCompletionChoiceDto> choices
) {
}
