// SPDX-License-Identifier: Apache-2.0
import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * The documentation sidebar. The Diátaxis spine (Tutorials / How-to / Concepts /
 * Reference) is the organising structure; "Get Started" carries the three thin
 * audience routers, and Examples / Release Notes / Contributing are structural pages.
 *
 * Each group references its directory via an `autogenerated` item, so every page in a
 * wired directory appears automatically. `scripts/lint-nav.mjs` enforces that no doc
 * lives outside a wired directory (or the explicit `index` entry), keeping the
 * "every doc is reachable from a sidebar" gate meaningful without hand-listing pages.
 */
const sidebars: SidebarsConfig = {
  docs: [
    {type: 'doc', id: 'index', label: 'Overview'},
    {
      type: 'category',
      label: 'Get Started',
      collapsed: false,
      items: [{type: 'autogenerated', dirName: 'get-started'}],
    },
    {
      type: 'category',
      label: 'Tutorials',
      items: [{type: 'autogenerated', dirName: 'tutorials'}],
    },
    {
      type: 'category',
      label: 'How-to Guides',
      items: [{type: 'autogenerated', dirName: 'how-to'}],
    },
    {
      type: 'category',
      label: 'Concepts',
      items: [{type: 'autogenerated', dirName: 'concepts'}],
    },
    {
      type: 'category',
      label: 'Reference',
      items: [{type: 'autogenerated', dirName: 'reference'}],
    },
    {
      type: 'category',
      label: 'Examples',
      items: [{type: 'autogenerated', dirName: 'examples'}],
    },
    {
      type: 'category',
      label: 'Release Notes',
      items: [{type: 'autogenerated', dirName: 'release-notes'}],
    },
    {
      type: 'category',
      label: 'Contributing',
      items: [{type: 'autogenerated', dirName: 'contributing'}],
    },
  ],
};

export default sidebars;
