// SPDX-License-Identifier: Apache-2.0
//
// Typed access to the build-time generated catalogue data (scripts/build-catalogue-data.mjs
// writes src/generated/catalogue-data.json — gitignored, regenerated by `npm run catalogue:build`
// before typecheck/test/build; see package.json). Vite bundles the JSON import natively: this is
// a fully static site with no runtime API to fetch from.
//
// The import is cast rather than left with its inferred literal-JSON type so the rest of the
// catalogue UI can work against a stable, hand-written interface instead of whatever exact
// literal shape the currently-generated fixture happens to have.

import rawCatalogueData from '@/generated/catalogue-data.json';
import type { RawExecutable } from '@/lib/renderWorkflowSvg';

/** One shipped workflow, as projected by build-catalogue-data.mjs. Optional fields the source
 * `workflow.json` does not carry are `null` — never a fabricated default. */
export interface CatalogueWorkflow {
  readonly id: string;
  readonly name: string;
  readonly description: string | null;
  readonly author: string | null;
  readonly contact: string | null;
  readonly version: string | null;
  readonly source: string | null;
  readonly schemaVersion: number;
  readonly steps: readonly RawExecutable[];
}

export interface CatalogueData {
  readonly workflows: readonly CatalogueWorkflow[];
  readonly catalogVersion: string;
  readonly minimumAgentForge4jVersion: string;
  readonly maximumAgentForge4jVersion: string | null;
  readonly workflowSchemaVersion: number;
}

export const catalogueData: CatalogueData = rawCatalogueData as unknown as CatalogueData;
